### ISSUE TITLE
shipping tax displayed twice

### ISSUE THREAD

**Issue by ghost** [firegento/firegento-pdf#106]
Using the current release version with Magento 1.8.1.
The tax for shipping and handling is displayed twice on my pdf invoices.

![2xversandsteuer](https://f.cloud.github.com/assets/6326082/1848304/fdd88ac8-7684-11e3-94df-0b0acf561a08.jpg)

**Comment by biotech** [comment]
Thanks for that fix! https://github.com/firegento/firegento-pdf/commit/0f96532a870a32ce1cea2730f6afbe14e1863407
