### ISSUE TITLE
Unable to add Notes programmatically

### ISSUE THREAD

**Issue by ghost** [firegento/firegento-pdf#109]
Hi,

i'm trying to add notes for Tax VAT-ID programmatically as stated in the FAQs over here..
https://github.com/firegento/firegento-pdf/wiki/FAQs

in Firegento_Pdf modules config.xml i added my observer block:

```
<events>
...
<!-- TAXVAT begin -->
<firegento_pdf_invoice_insert_note>
    <observers>
        <firegento_eu>
            <class>firegento_eu/observer</class>
            <method>addInvoiceTaxVatNotes</method>
        </firegento_eu>
    </observers>
</firegento_pdf_invoice_insert_note>
<!-- TAXTVAT end -->
...
</events>
```

the path to my module and observer.php is the following:
/app/code/Firegento/EU/Observer.php,  the code content follows:

```
<?php
class FireGento_EU_Observer
{
    public function addInvoiceTaxVatNotes(Varien_Event_Observer $observer)
    {
        $result = $observer->getResult();
        $notes  = $result->getNotes();
        $notes[] = 'Your VAT ID is: XXXXXX';
        $result->setNotes($notes);
        return $this;
    }
}
```

am I missing something?

thank you in advance

**Comment by dschallert** [comment]
Short folllow up question.

How would I access the $order or $customer inside my model?

thanks
