### ISSUE TITLE
Not enough allocated space for billing address 

### ISSUE THREAD

**Issue by sasoriza** [firegento/firegento-pdf#133]
If customers fill out every address field (Name, Company, 2 row Address, City & ZIP, Country, Telephone) the address will be printd on top of the "Invoice" heading.

**Comment by sasoriza** [comment]
Did your invoice include a logo?
I just updated to 1.3.0 and am still seeing the issue:
![firegento](https://cloud.githubusercontent.com/assets/2168304/7809036/b029a770-0397-11e5-8dd8-ee6445a2c1c0.jpg)

**Comment by Schrank** [comment]
Are you sure, you are using the current version? The color seems to be a rewrite, so maybe you accidentally use the wrong code? I have no clue, why I can't reproduce this. Can you copy all your settings from `core_config_data` about firegento_pdf and put it here?

**Comment by sprankhub** [comment]
@Schrank not sure if this is the issue, but did you also had a big logo on the left hand side?

**Comment by Schrank** [comment]
no clue, will check again with the new infos.

**Comment by sasoriza** [comment]
I compared all my files and realized I did copy over a modification most likely responsible for this. As you can see on my screenshot, customer name and invoice number are on the same line, in the default setup customer name would be higher up. I changed line 407 in Abstract.php (instead of 692 I am only substracting 673) to compensate for my logo and to make sure customer name and invoice number appear to be in the same line.
I now edited some more of that file and moved everything down a bit. Sorry, not sure why I didn't try this earlier...

![firegento2](https://cloud.githubusercontent.com/assets/2168304/7811024/558eec3e-03a7-11e5-8ded-117841575129.jpg)


By the way, did define a new color by changing $this->colors['grey1'] in Abstract.php in case you are wondering about the blue.

**Comment by Schrank** [comment]
Great to hear and great you fixed your problem. And I think we have yet another feature I would like to implement https://github.com/firegento/firegento-pdf/issues/241
