### ISSUE TITLE
PDF Invoice TAX Round ISSUE

### ISSUE THREAD

**Issue by Dung123** [firegento/firegento-pdf#160]
Hi,

I generate an Invoice with 6 Items x 10 Euro Gesamt Brutto it shows me 60,03 €. I use 7 % Tax ermässig Besteuerung. Normaly it should be exact 60,00 €. Is it maybe a bug? I think a round problem. The Email Confirmation show me the correct Gesamt Brutto also the admin Panel is correct only the PDF Invoice is wrong. If I use the Magento Standard it is also correct.

Sung

**Comment by sprankhub** [comment]
Just tested this and can confirm the issue. But it is a Magento issue, not an issue of this extension. The Magento admin shows exactly the same:

![prob](https://cloud.githubusercontent.com/assets/930199/6251363/cfc28ef8-b793-11e4-8180-d9dd4e0bd940.png)

**Comment by sprankhub** [comment]
Just checked again and you can solve the issue with the [BetterPriceRounding extension](https://github.com/therouv/Magento-BetterPriceRounding). Mind that this will only affect new orders/invoices.
