### ISSUE TITLE
Use Our Engine as the Default Engine?

### ISSUE THREAD

**Issue by sprankhub** [firegento/firegento-pdf#191]
Many people expect that an extension just works out-of-the-box (see e.g. https://github.com/firegento/firegento-pdf/issues/189). They want to install it and directly see the results. This is why we should think of changing the default engine to the FireGento one. Currently, the user has to change the engine from the Magento engine to the FireGento engine manually. I think this is not user-friendly. Why does the user install our extension? Because he actually *wants* another engine.

What do you think @Schrank, @daim2k5 and all others?

**Comment by Schrank** [comment]
Fixed by @laebs, thanks for that!
