### ISSUE TITLE
Adressfeld des Kunden fehlerhaft

### ISSUE THREAD

**Issue by carstenclaassen** [firegento/firegento-pdf#199]
Die PLZ und Ort stehen direkt neben der Strasse. Wie kann das geändert werden `?

**Comment by Schrank** [comment]
Das adresstemplate für pdfs bei system > konfiguration > kunde ändern

Bitte.

Von unterwegs gesendet

**Comment by carstenclaassen** [comment]
Und wie bekomme ich die rechnungsnummer ins adressfeld ?

 

Von: Fabian Blechschmidt [mailto:notifications@github.com] 
Gesendet: Samstag, 3. Januar 2015 10:25
An: firegento/firegento-pdf
Cc: carstenclaassen
Betreff: Re: [firegento-pdf] Adressfeld des Kunden fehlerhaft (#199)

 

Das adresstemplate für pdfs bei system > konfiguration > kunde ändern 

Bitte. 

Von unterwegs gesendet

**Comment by Schrank** [comment]
Can we please change to english?

I'm sorry. You don't. Why do you want to have the invoice number in the address field?

Whatever reason you has. To do this, I think you have to implement either your own engine, or add an empty line to the adress field and then place perfectly into this line your number:
https://github.com/firegento/firegento-pdf/wiki/FAQs#how-can-i-put-some-fancy-stuff-wherever-i-want-to-without-writing-my-own-engine
