### ISSUE TITLE
Include product options in invoice

### ISSUE THREAD

**Issue by danielchicote** [firegento/firegento-pdf#202]
Is possible to include special options, atributes or the product configuration in the invoices?

**Comment by sprankhub** [comment]
What exactly do you mean?

- Custom options are indeed not printed. This topic has been discussed in https://github.com/firegento/firegento-pdf/issues/196. I would be open for a configuration which enables to show the custom options without the prices (the same how we handle configurable products).
- Selected attributes of configurable products are already printed.
- I do not know what you mean by product configuration.

**Comment by danielchicote** [comment]
Excuse me, i was wrong, the options are displayed by default.

And, it will be possible to include the product images?

**Comment by sprankhub** [comment]
Not by default. I guess only very few people need that. You can write your own engine and write a custom renderer. The [wiki](https://github.com/firegento/firegento-pdf/wiki) and [this blog post](http://www.webguys.de/magento/tuerchen-04-firegento-pdf-developers/) may help you to get started.

Another option is to hire one of the [contributors](https://github.com/firegento/firegento-pdf/graphs/contributors).

**Comment by danielchicote** [comment]
Oh, thanks for the info. :+1:
