### ISSUE TITLE
Downloadproducts are broken

### ISSUE THREAD

**Issue by Schrank** [firegento/firegento-pdf#203]
Mir ist bei FireGentoPDF beim Testen was aufgefallen:
Nach meinem Anschein nach scheinen Downloadable Products noch nicht berücksichtigt worden zu sein.  Jedenfalls fällt das über die PDF Engine "Standard Deutschland" erzeugte Dokument an dieser Stelle aus dem sonst tollem Raster.

![firegentopdf bug downloadable products](https://cloud.githubusercontent.com/assets/379680/5801252/43bacaae-9fe9-11e4-9ee2-7b0caf13020c.png)

**Comment by sprankhub** [comment]
Just tried it with the latest development version and cannot reproduce the issue:

![invoice-download](https://cloud.githubusercontent.com/assets/930199/6251126/65c6b854-b792-11e4-82a8-227d7bac1614.png)
