### ISSUE TITLE
Add Screenhots to README / Wiki

### ISSUE THREAD

**Issue by peterjaap** [firegento/firegento-pdf#207]
Maybe include screenshots of the Magento configuration options of this extension in the README?

**Comment by sprankhub** [comment]
Good idea. Although I do not know if we should blow up the README. I would vote for another [FAQ](https://github.com/firegento/firegento-pdf/wiki/FAQs) entry.

**Comment by sprankhub** [comment]
See https://github.com/firegento/firegento-pdf/wiki/FAQs#what-exactly-can-i-configure

**Comment by Schrank** [comment]
we should add Customer IP, added Tax settings

**Comment by sprankhub** [comment]
@Schrank I added a hint for the customer IP. I vote against adding the tax settings since they are very difficult to understand. If there is a good explanation for them at some time, we can still add them. If you think we should add them anyway, feel free to reopen.
