### ISSUE TITLE
Feature request: add notes based on Shipping Country

### ISSUE THREAD

**Issue by senders** [firegento/firegento-pdf#209]
For germany it is important to add special notes to the invoice for special shipping countries, for example "steuerfreie Auslieferung"

**Comment by Schrank** [comment]
I think this feature is very special and quite complex to solve generic. But it is very easy to solve for your special case:

Just write an observer, listen on `firegento_pdf_invoice_insert_note ` check the country and add the note.

**Comment by sprankhub** [comment]
I am not quite sure if this is really special. We had this topic on [Magento SE](https://magento.stackexchange.com/questions/43366/add-note-on-invoices-for-specific-countries), I think we had it in the IRC and I had the issue with a customer. So it may be a good idea to solve it generically. I think theoretically every shop owner who ships to certain countries has this issue.

**Comment by senders** [comment]
Thanks Schrank, yes I know this possibility but I also agree with sprankhub that this is a must have feature for all of those who want to send invoices into another country. A lawyer told us that this is a must have feature we have to implement.
Great would be a filter like it is implemented in the checkout price rules, so everyone could add notes concerning special conditions.

**Comment by Schrank** [comment]
Ok, so the first step is to implement a country -> add note feature :-)

**Comment by sprankhub** [comment]
What do you think @Schrank? Okay to merge? https://github.com/firegento/firegento-pdf/commit/b9dcfcaf49bba22adb1bf98a26070855639bd00c

**Comment by sprankhub** [comment]
Looks like that:
![image](https://cloud.githubusercontent.com/assets/930199/7890255/1e83aab8-0645-11e5-919b-eff2f8411b11.png)

**Comment by Schrank** [comment]
Looks nice! Give me one night in my own bed, then I'll have a look on the code and merge it!

**Comment by sprankhub** [comment]
This is now implemented.
