### ISSUE TITLE
PDF Filesize if order has bundle items

### ISSUE THREAD

**Issue by michihu** [firegento/firegento-pdf#210]
Hi,
Firegento is generating my invoices and packing slips. The filesize of the pdf is 150kb which is fine. But when the order contains a bundle product the filesize gets up to 1mb. And I cannot figure out why that.

I even deleted the print of the item for testing purposes but no results, still 980 kb.

Any idea? there is no special font loaded or anything. also the PDF size is fine if there is no bundle item in the order.

**Comment by michihu** [comment]
in the bundle file we now defined the font itself. now its fixed. I guess in the bundle it still took the included font that magento uses by default.
For other people having this issue would be great to fix that in the firegento module itself i guess.

**Comment by sprankhub** [comment]
Never heard of that issue. If this is the case, this should definitely be fixed.

**Comment by sprankhub** [comment]
@michihu should be fixed in the current development branch. Thanks for the report!
