### ISSUE TITLE
FireGento MadgeSetup

### ISSUE THREAD

**Issue by divestyle** [firegento/firegento-pdf#211]
I do apologise if this is not the correct place.

I recently installed MadgeSetup from FireGento so that I could take advantage of the TAX / VAT display functionality.

I noticed after installation that I acquired new check boxes on the one page checkout screen

I agree [Show]
I have read the Business Terms and agree with them. [Show]
I have read the Right of Revocation. [Show]

These seem to have been installed by running the MadgeStup and not un-ticking the relevant boxes before hitting the confog button in the System panel.

I have since tried to reinstall without the check boxes being ticked, removing the extension through Magento Connect, all to no avail.

What I cannot find is any process defining how to completely remove MadgeSetup plus all of its files that it produces as part of the initial setup.

 At this point I would settle for removing the additional check boxes on the checkout page but cannot locate the relevant file to do so.

Any help would be greatly appreciated.

Thanks in advance from a novice Magento person.

**Comment by sprankhub** [comment]
I moved this issue to the proper project and answered there: https://github.com/firegento/firegento-magesetup/issues/133
