### ISSUE TITLE
Zwischensumme/Subtotal

### ISSUE THREAD

**Issue by ming2014** [firegento/firegento-pdf#213]
![20150206104621](https://cloud.githubusercontent.com/assets/6830913/6077511/03a35020-adf0-11e4-8611-a424e2d9bd90.png)

Hallo
Nach der Installation habe ich hier ein Problem, wenn ich die Punkt (Extention J2T Reward Points )eingelöstet habe, dann bekomme ich die Zwishcensumme falsch.
Hat jemand auch solche Probleme.

Vielen Dank

Grüßen

Ming

**Comment by Schrank** [comment]
Hi ming. Please use english, so everyone understands the problem.

I never heard of this extension and I think it isn't of broad interest, therefore I wouldn't invest time here. But when you find the problem we are happy if you submit a PR.

**Comment by sprankhub** [comment]
@ming2014 could you please also post a screenshot how the invoice is shown in the admin area? Our invoice PDF should show exactly the same data which is presented there.

**Comment by ming2014** [comment]
but when I used a couple,I have the same problem
![20150206115525](https://cloud.githubusercontent.com/assets/6830913/6078252/718385d6-adf7-11e4-80f8-e1e6ecf0f4e6.png)

Admin Area:

![1](https://cloud.githubusercontent.com/assets/6830913/6078316/c53cc3fe-adf7-11e4-9f21-e37233c49684.png)
![2](https://cloud.githubusercontent.com/assets/6830913/6078319/cad47d0c-adf7-11e4-97b6-91927a958ba1.png)
![3](https://cloud.githubusercontent.com/assets/6830913/6078323/ce81c036-adf7-11e4-83e8-d3d0b02fe9d3.png)

thank you very much

ming

**Comment by sprankhub** [comment]
I would like to see a screenshot of the admin view of the invoice. Sales - Invoices - Select Invoice - make a screenshot.

**Comment by ming2014** [comment]
Sorry , i can not find Sales - Invoices - Select Invoice , i use magento 1.81.1
![4](https://cloud.githubusercontent.com/assets/6830913/6079225/b35c2188-ae02-11e4-937b-c6c6b9261829.png)
![5](https://cloud.githubusercontent.com/assets/6830913/6079227/b7a101c8-ae02-11e4-9f67-c243bbc17505.png)

thanks

ming

**Comment by sprankhub** [comment]
This is the configuration section. You should have a look at the top of the page in the top menu.

**Comment by Schrank** [comment]
You have a top menu called Sales in English and Invoices.

Screenshot in german:
![bildschirmfoto 2015-02-06 um 13 24 31](https://cloud.githubusercontent.com/assets/379680/6079281/93befea8-ae03-11e4-818d-d15877e62ea5.png)

**Comment by ming2014** [comment]
![6](https://cloud.githubusercontent.com/assets/6830913/6079317/027ff1bc-ae04-11e4-9b73-783f5da12b39.png)

**Comment by Schrank** [comment]
For some weird reason, the row total is wrong.

![213](https://cloud.githubusercontent.com/assets/379680/7883294/b7d958a0-0615-11e5-9812-a578f4023108.jpg)

**Comment by sprankhub** [comment]
I cannot reproduce this issue.
