### ISSUE TITLE
Need help to change text

### ISSUE THREAD

**Issue by happyfabric** [firegento/firegento-pdf#214]
![screenshot](https://cloud.githubusercontent.com/assets/8696818/6168886/816fff2a-b2c9-11e4-9c44-4d96083c7fb7.png)
Hi all. I'm going nuts. I'm trying to change the text in the invoice pdf. It's possible to change the text with the green frame in the FireGento_PDF.csv but not the text in the red frame. I searched thru different XX_mage.csv without a result.

Can someone tell me how to change it please?

thx

**Comment by Schrank** [comment]
Rabatt (resetet) is the name of the cart discount rule you entered in the backen.

and I would say the Gesamt (inkl. Steuern) comes from: https://github.com/riconeitzel/German_LocalePack_de_DE/blob/preview/app/locale/de_DE/Mage_Tax.csv#L58

**Comment by happyfabric** [comment]
(resetet) was in this case the rule. i know that. But it it not possible to
change "Rabatt" and Gesamt (inkl. Steuern). I did it like you said. But it
did not work.


________________________________

HappyFabric.de
GSE Texprint Solutions GmbH
Stubenrauchstraße 49
12161 Berlin

Tel: ++49 (0) 30 / 897 47 348
Fax: ++49 (0) 30 / 897 32 32 -2
E-Mail: kontakt@happyfabric.de
Shop: www.happyfabric.de
Facebook: www.facebook.com/HappyFabric

2015-02-12 16:59 GMT+01:00 Fabian Blechschmidt <notifications@github.com>:

**Comment by Schrank** [comment]
Hook into \Mage_Core_Model_Translate::_getTranslatedString and check what prefix this text has.

Then just add "Mage_Sales::Grand Total (Incl. Tax)" or "FireGento_Pdf::Grand Total (Incl. Tax)" or "Mage_Tax::Grand Total (Incl. Tax)" to translate.csv in frontend and backend

**Comment by happyfabric** [comment]
Hook into \Mage_Core_Model_Translate::_getTranslatedString ???
Sorry. I don't know what that means....

**Comment by Schrank** [comment]
Use xdebug or a debugger of your choice and check in which module the string is translated (hopefully you are a developer or has some one who can do this) and then add the right string with the correct prefix to your theme base translate.csv
