### ISSUE TITLE
Overwrite \Mage_Adminhtml_Sales_OrderController::pdfinvoicesAction to include custom invoice name

### ISSUE THREAD

**Issue by KR-A** [firegento/firegento-pdf#215]
Hi.
How and where can I change the file name:
From invoice to RECHNUNG or shipment to VERSAND?
Can I use the customer name to add to the file name?

thanks

**Comment by Schrank** [comment]
sure, that it is for :-)

**Comment by KR-A** [comment]
Vielen Dank. :-(

**Comment by daim2k5** [comment]
Under Configuration->SALES->PDF Print-outs->Invoice "Filename Export Pattern"

**Comment by Schrank** [comment]
Oh sorry, misread the question :/ Instead of customer I read custom name and therefore I thought you asked, whether you can use this field to change the name. Thanks @daim2k5  and sorry @KR-A for seeming so rude

**Comment by KR-A** [comment]
Sales -> Orders -> Order No. 123456 -> Invoice. Everything perfect. Thanks !!

Sales -> Orders -> SELECT visble order no. 12345 and select actions "Print": does not work. Here comes invoice2015-02-15_16-10-02.pdf

Is there a solution?

**Comment by Schrank** [comment]
I think this controller is not yet overwritten. This needs to be done by someone. You can use https://github.com/firegento/firegento-pdf/blob/development/src/app/code/community/FireGento/Pdf/controllers/Adminhtml/Sales/Order/InvoiceController.php as a starting point.

**Comment by KR-A** [comment]
I have 3 Controller overwritten.
No change.
It does not.

**Comment by Schrank** [comment]
Do you overwrite `\Mage_Adminhtml_Sales_OrderController::pdfinvoicesAction` ? And are you sure, your code is called?

**Comment by KR-A** [comment]
This ist the code from InvoiceController.php:


<?php
/**
 * This file is part of a FireGento e.V. module.
 *
 * This FireGento e.V. module is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * This script is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
 *
 * PHP version 5
 *
 * @category  FireGento
 * @package   FireGento_Pdf
 * @author    FireGento Team <team@firegento.com>
 * @copyright 2013 FireGento Team (http://www.firegento.com)
 * @license   http://opensource.org/licenses/gpl-3.0 GNU General Public License, version 3 (GPLv3)
 */

require('Mage/Adminhtml/controllers/Sales/Order/InvoiceController.php');

/**
 * Class FireGento_Pdf_Adminhtml_Sales_Order_InvoiceController
 *
 * @category FireGento
 * @package  FireGento_Pdf
 * @author   FireGento Team <team@firegento.com>
 */
class FireGento_Pdf_Adminhtml_Sales_Order_InvoiceController
    extends Mage_Adminhtml_Sales_Order_InvoiceController
{

    /**
     * Create pdf for current invoice
     */
    public function printAction()
    {
        $this->_initInvoice();
        if ($invoiceId = $this->getRequest()->getParam('invoice_id')) {
            if ($invoice = Mage::getModel('sales/order_invoice')
                ->load($invoiceId)
            ) {
                $pdf = Mage::getModel('sales/order_pdf_invoice')
                    ->getPdf(array($invoice));
                $this->_prepareDownloadResponse(
                    Mage::helper('firegento_pdf')
                        ->getExportFilename('invoice', $invoice),
                    $pdf->render(), 'application/pdf'
                );
            }
        } else {
            $this->_forward('noRoute');
        }
    }

}

**Comment by Schrank** [comment]
What do you mean by this?

**Comment by KR-A** [comment]
Yo write: "Do you overwrite  \Mage_Adminhtml_Sales_OrderController::pdfinvoicesAction  ? "

What do you mean by this?

**Comment by Schrank** [comment]
This is the controller action which handles the pdf printing in the order view. I don't know why, but it seems, that our module isn't overwriting this action yet. So what you want is not available as feature yet (imho). To implement this feature, someone needs to overwrite this controller action, we will. When we find some time. If you need it earlier, either you do it or find some one who does it :-)

**Comment by KR-A** [comment]
Ok. Thanks for the work.

**Comment by sprankhub** [comment]
The problem is that the placeholders ({{invoice_id}}, {{order_id}}, {{customer_id}}, {{customer_name}}, {{customer_firstname}}, {{customer_lastname}}) are not applicable if there is more than one document. Hence, I vote for a new configuration field like "Filename Export Pattern for Multiple Documents".

**Comment by KR-A** [comment]
Thanks for the information.
These are my placeholder. Rechnung Nr. {{}} invoice_id vom % d% m% Y {{{{}} customer_firstname customer_lastname}}

Question: An Extension for Print Order Confirmation documents. Is it possible to integrate it?

**Comment by sprankhub** [comment]
I do not exactly know what you mean. But I can tell you that there is another issue #200 which handles the order PDFs.
