### ISSUE TITLE
Barcodes should also be displayable on invoices

### ISSUE THREAD

**Issue by dakira** [firegento/firegento-pdf#217]
The workflow of a client requires barcodes on the invoices instead of the shipments.

I'm already using this. If there's any interest or no objections, I'll create a pull-request.

**Comment by Schrank** [comment]
If you add a system.xml to switch it on and off I'm fine with this

**Comment by sprankhub** [comment]
Yeah, if it is configurable like the one from the shipment, than it is a good feature. Thank you!

**Comment by dakira** [comment]
Okay, PR coming soon.
