### ISSUE TITLE
Tax rate is not shown

### ISSUE THREAD

**Issue by enesgenc** [firegento/firegento-pdf#218]
Dear friends, 

i have installed magento 1.8
-german setup and firegento pdf where also installed

My problem is, i want on my invoice pdf instead of "USt." the word "Mehrwertsteuer (19%)"

how can i change it?

 
![screenshot](https://cloud.githubusercontent.com/assets/11048510/6234028/927f3044-b6d7-11e4-84fe-5b71fc228cf6.JPG)

Anyone a idea?

Many thanks
Enes

**Comment by Schrank** [comment]
I find neither in MageSetup nor in FireGento_Pdf the Term Ust. in translation files, therefore I assume it is your tax label. Change it under: Sales > Tax.

Or you have it in some translation file. Just grep/search for it.

HTH

**Comment by enesgenc** [comment]
Dear Schrank,

thank you for your fast answer. But i can not find anywhere..

/app/locale/de_DE/mage_tax.csv 

I am written for tax the translation "Mehrwertsteuer (19%)" but on the invoice pdf i get "USt."

In sales > tax, where can i change name? or do you know where everywhere exists translation files.

Many Thanks
enes

**Comment by Schrank** [comment]
@sprankhub any idea on this?

**Comment by sprankhub** [comment]
The translation comes from [our extension](https://github.com/firegento/firegento-pdf/blob/development/src/app/locale/de_DE/FireGento_Pdf.csv#L30). Hence, this translation has to be changed. Possibilities:

1. Directly change it under `app/locale/de_DE/FireGento_Pdf.csv`. You changes will be lost after each upgrade.
2. Build an extension which depends on `FireGento_Pdf` and which adds an adminhtml translation file (see e.g. [here](http://stackoverflow.com/a/4674680/719023)). The following content should work then:

        "FireGento_Pdf::USt.","Mehrwertsteuer (19%)"

**Comment by enesgenc** [comment]
thank you sprankhub, 

i think i have done anything wrong. Now the invoice pdf is in english language.

where i can switch it in german again?

@sprankhub

**Comment by sprankhub** [comment]
@enesgenc what did you do exactly? If you edit `app/locale/de_DE/FireGento_Pdf.csv`, then you should keep everything untouched except the line which you want to change.

**Comment by enesgenc** [comment]
i have changed only at the line tax

Tax,"Mehrwertsteuer (19%)"

than i made an overwrite with the file on the webspace.

**Comment by enesgenc** [comment]
the total invoice is now in english language

**Comment by sprankhub** [comment]
Replace the whole file `app/locale/de_DE/FireGento_Pdf.csv` with the following content: http://pastebin.com/fD3cRvTG

**Comment by enesgenc** [comment]
I replaced, but i get the invoice in english language again

**Comment by enesgenc** [comment]
but i done only this part

1. Directly change it under app/locale/de_DE/FireGento_Pdf.csv. You changes will be lost after each upgrade.

**Comment by enesgenc** [comment]
should i do the second part too?

**Comment by sprankhub** [comment]
No, one of the two is enough. Sorry, but please check again or hire a developer.

**Comment by enesgenc** [comment]
:)) but for 10 minutes it was in german language. i done this first solutions suggest of you. 
hmmm

**Comment by enesgenc** [comment]
Hallo @sprankhub, 

Sie sind ja Deutsch, habe ich zufällig auf weiteren themen gesehen.
ICh habe mein Problem leider nicht lösen können, kein Plan wieso jetzt die komplette Rechnung wieder auf Englisch gewechselt hat.

Magento 1.8
FIregento und German Setup installiert.

Gibts da i.welche Einstellungen wo man die Sprache mit klicks umswitchen kann? Wäre echt dankbar wenn wir das Problem lösen können.

Vielen Dank für die Bemühungen.

VG
Enes

**Comment by sprankhub** [comment]
Stick to English as more people understand.

The language of the documents is taken from the configured language under System - Configuration - General - Locale Options - Locale.

**Comment by enesgenc** [comment]
the location is "germany", store also.  i ve changed only this line on the firegento_csv after overwrite i got this problem
![screenshot_invoice](https://cloud.githubusercontent.com/assets/11048510/6266948/e431c622-b83f-11e4-9a1e-be28661a4777.JPG)

**Comment by enesgenc** [comment]
as you can see, Price (incl.tax), invoice number and so on.. at the footer is everything also in english

**Comment by sprankhub** [comment]
Last try: Post your file `app/locale/de_DE/FireGento_Pdf.csv`.

**Comment by enesgenc** [comment]
"Invoice maturity: %s days,""Fälligkeit der Rechnung: %s Tage"""
"Invoice Maturity,""Fälligkeit der Rechnung"""
"Days after the invoice is due. Leave this field blank to hide the message on the invoice.,""Tage, nach denen die Rechnung fällig ist. Feld leer lassen, um den Text auf der Rechnung zu verbergen."""
"Invoice is payable immediately,""Die Rechnung ist sofort fällig."""
"Invoice date is equal to delivery date.,""Rechnungsdatum ist gleich dem Lieferdatum."""
"Payment method:,""Zahlungsart:"""
"Shipping method:,""Versandart:"""
"Payment method: %s,""Zahlungsart: %s"""
"Shipping method: %s,""Versandart: %s"""
"Page,""Seite"""
"Telephone:,""Telefon:"""
"Fax:,""Fax:"""
"E-Mail:,""E-Mail:"""
"Web:,""Web:"""
"Bank name:,""Kreditinstitut:"""
"Account:,""Kontonummer:"""
"Bank number:,""BLZ:"""
"Account owner:,""Kontoinhaber:"""
"SWIFT:,""SWIFT:"""
"IBAN:,""IBAN:"""
"Tax number:,""Steuernummer:"""
"VAT-ID:,""USt-IdNr.:"""
"Register number:,""HRB Nummer:"""
"CEO:,""Geschäftsführer:"""
"Pos,""Pos."""
"No.,""Artikelnummer"""
"Description,""Beschreibung"""
"Price (excl. tax),""Preis (Netto)"""
"Amount,""Betrag"""
"Tax,""Mehrwertsteuer (19%)"""
"Total,""Summe"""
"Invoice,""Rechnung"""
"Creditmemo,""Gutschrift"""
"Order number:,""Bestellnummer:"""
"Invoice number:,""Rechnungsnummer:"""
"Shipment number:,""Lieferscheinnummer:"""
"Creditmemo number:,""Gutschriftsnummer:"""
"Customer number:,""Kundennummer:"""
"Customer IP:,""Kunden IP:"""
"Invoice date:,""Rechnungsdatum:"""
"Shipping date:,""Versanddatum:"""
"Date:,""Datum:"""
"Additional tax %s,""Zusätzliche Steuern %s"""
"Subtotal:,""Zwischensumme:"""
"Shipping:,""Versand:"""
"Grand Total:,""Gesamtsumme:"""
"Guestorder,""Gastbestellung"""
"PDF Engine,""PDF Engine"""
"Note,""Notiz"""
"Printed on every invoice.,""Wird auf jede Rechnung gedruckt."""
"Printed on every shipment.,""Wird auf jeden Lieferschein gedruckt."""
"Printed on every credit memo.,""Wird auf jede Gutschrift gedruckt."""
"PDF Creation,""PDF Erstellung"""
"Sender Address Bar,""Absenderadresse"""
"Show Footer,""Zeige Footer"""
"Logo Position,""Logo Position"""
"Left,""Links"""
"Center,""Mittig"""
"Right,""Rechts"""
"Standard Magento,""Standard Magento"""
"Standard FireGento,""Standard FireGento"""
"Show Payment Method,""Zahlungsart anzeigen"""
"Hide payment method,""Nicht anzeigen"""
"Header,""Dokumenten-Kopf"""
"Notes area,""Notizbereich"""
"Position of payment method on invoice.,""Position der Zahlungart auf der Rechnung."""
"Show Shipping Method,""Versandart anzeigen"""
"Hide shipping method,""Nicht anzeigen"""
"Position of shipping method on invoice.,""Position der Versandart auf der Rechnung."""
"Position of shipping method on shipment.,""Position der Versandart auf dem Lieferschein."""
"not to be listed,""nicht aufzulisten"""
"Show Invoice Comments,""Rechnungskommentare anzeigen"""
"Show Shipment Comments,""Lieferscheinkommentare anzeigen"""
"Show Credit Memo Comments,""Gutschriftenkommentare anzeigen"""
"Show Item Discount,""Rabatt auf Artikelebene anzeigen"""
"You get a discount of %s.,""Sie erhalten einen Rabatt von %s."""
"Tax amount,""Steuerbetrag"""
"Price (incl. tax),""Preis (Brutto)"""
"Subtotal (incl. tax),""Zwischensumme (Brutto)"""
"Order of price columns of items,""Reihenfolge der Spalten in der Artikelliste"""
"Define the order by moving the following items using your mouse:,""Legen Sie die Reihenfolge durch Verschieben der Einträge mit der Maus fest:"""
"Tax rate,""Steuersatz"""
"Total (incl. tax),""Gesamt (brutto)"""
"Show Date Notice,""Anzeige des Datums im Notizbereich"""
"Show Notice: Invoice date is equal to delivery date.,""Zeige im Notizbereich: Rechnungsdatum ist gleich dem Lieferdatum."""
"Show Customer Number,""Kundennummer anzeigen"""
"Full width,""volle Breite"""
"Full width means that the logo starts at the upper left corner and is drawn to the right edge. There is no left or right margin for printing.,""""""volle Breite"""" bedeutet, dass das Logo über die komplette Seite von oben links bis zum rechten Rand gezogen wird. Es verbleibt kein Druckrand."""
"Show Order ID as Barcode,""Bestellnummer als Barcode anzeigen."""
"Prints the order ID as a barcode on the right hand side.,""Zeigt die Bestellnummer als Barcode auf der rechten Seite an."""
"Left: Customer address left, Invoice details right. Right: Invoice details left, Customer address right.,""Links: Kundenadresse links, Rechnungsdetails rechts. Rechts: Rechnungsdetails links, Kundenadresse rechts"""
"Show address above shipping/invoice address,""Zeige Adresse über Empfängeradresse"""
"Fonts for PDF Creation,""Schriftarten für PDF Erstellung"""
"You can upload your own fonts (*.ttf, *.otf) instead of using Zends Helvetica,""Sie können eigene Schriften (*.ttf, *.otf) hochladen, statt Zends Helvetica zu benutzen."""

**Comment by sprankhub** [comment]
Simple. The file is in the wrong format. The format has to be:

    "English text","Deutscher Text"

See here: https://raw.githubusercontent.com/firegento/firegento-pdf/development/src/app/locale/de_DE/FireGento_Pdf.csv

**Comment by enesgenc** [comment]
(y) (y) super vielen Dank! hat funktioniert. 

now its working!!! thanks @sprankhub

**Comment by enesgenc** [comment]
last small question, how can i disable client ip (Kunden IP) at the invoice pdf ?

**Comment by Schrank** [comment]
Customer > Customer Configuration

**Comment by enesgenc** [comment]
there is no option about kunden ip 

on system > Kunden > kunderkonfiguration

**Comment by sprankhub** [comment]
System - Configuration - Sales - General

**Comment by enesgenc** [comment]
Great! Thanks!!!!!

**Comment by eddy2009** [comment]
Hi,
I have long tried but without success. I can not change the cvs file and upload it. Excel displays errors. Who can provide me the modified cvs file.

This is my FireGento_Pdf.csv

"Invoice maturity: %s days","Fälligkeit der Rechnung: %s Tage"
"Invoice Maturity","Fälligkeit der Rechnung"
"Days after the invoice is due. Leave this field blank to hide the message on the invoice.","Tage, nach denen die Rechnung fällig ist. Feld leer lassen, um den Text auf der Rechnung zu verbergen."
"Invoice is payable immediately","Die Rechnung ist sofort fällig."
"Invoice date is equal to delivery date.","Rechnungsdatum ist gleich dem Lieferdatum."
"Payment method:","Zahlungsart:"
"Shipping method:","Versandart:"
"Payment method: %s","Zahlungsart: %s"
"Shipping method: %s","Versandart: %s"
"Page","Seite"
"Telephone:","Telefon:"
"Fax:","Fax:"
"E-Mail:","E-Mail:"
"Web:","Web:"
"Bank name:","Kreditinstitut:"
"Account:","Kontonummer:"
"Bank number:","BLZ:"
"Account owner:","Kontoinhaber:"
"SWIFT:","SWIFT:"
"IBAN:","IBAN:"
"Tax number:","Steuernummer:"
"VAT-ID:","USt-IdNr.:"
"Register number:","HRB Nummer:"
"CEO:","Geschäftsführer:"
"Pos","Pos."
"No.","Artikelnummer"
"Description","Beschreibung"
"Price (excl. tax)","Preis (Netto)"
"Amount","Betrag"
"Tax","USt."
"Total","Summe"
"Invoice","Rechnung"
"Creditmemo","Gutschrift"
"Order number:","Bestellnummer:"
"Invoice number:","Rechnungsnummer:"
"Shipment number:","Lieferscheinnummer:"
"Creditmemo number:","Gutschriftsnummer:"
"Customer number:","Kundennummer:"
"Customer IP:","Kunden IP:"
"Invoice date:","Rechnungsdatum:"
"Shipping date:","Versanddatum:"
"Date:","Datum:"
"Additional tax %s","Zusätzliche Steuern %s"
"Subtotal:","Zwischensumme:"
"Shipping:","Versand:"
"Grand Total:","Gesamtsumme:"
"Guestorder","Gastbestellung"
"PDF Engine","PDF Engine"
"Note","Notiz"
"Printed on every invoice.","Wird auf jede Rechnung gedruckt."
"Printed on every shipment.","Wird auf jeden Lieferschein gedruckt."
"Printed on every credit memo.","Wird auf jede Gutschrift gedruckt."
"PDF Creation","PDF Erstellung"
"Sender Address Bar","Absenderadresse"
"Show Footer","Zeige Footer"
"Logo Position","Logo Position"
"Left","Links"
"Center","Mittig"
"Right","Rechts"
"Standard Magento","Standard Magento"
"Standard Germany","Standard Deutschland"
"Show Payment Method","Zahlungsart anzeigen"
"Hide payment method","Nicht anzeigen"
"Header","Dokumenten-Kopf"
"Notes area","Notizbereich"
"Position of payment method on invoice.","Position der Zahlungart auf der Rechnung."
"Show Shipping Method","Versandart anzeigen"
"Hide shipping method","Nicht anzeigen"
"Position of shipping method on invoice.","Position der Versandart auf der Rechnung."
"Position of shipping method on shipment.","Position der Versandart auf dem Lieferschein."
"not to be listed","nicht aufzulisten"
"Show Invoice Comments","Rechnungskommentare anzeigen"
"Show Item Discount","Rabatt auf Artikelebene anzeigen"
"You get a discount of %s.","Sie erhalten einen Rabatt von %s."
"Tax amount","Steuerbetrag"
"Price (incl. tax)","Preis (Brutto)"
"Subtotal (incl. tax)","Zwischensumme (Brutto)"
"Order of price columns of items","Reihenfolge der Spalten in der Artikelliste"
"Define the order by moving the following items using your mouse:","Legen Sie die Reihenfolge durch Verschieben der Einträge mit der Maus fest:"
"Tax rate","Steuersatz"
"Total (incl. tax)","Gesamt (brutto)"
"Show Date Notice","Anzeige des Datums im Notizbereich"
"Show Notice: Invoice date is equal to delivery date.","Zeige im Notizbereich: Rechnungsdatum ist gleich dem Lieferdatum."
"Show Customer Number","Kundennummer anzeigen"
"Full width","volle Breite"
"Full width means that the logo starts at the upper left corner and is drawn to the right edge. There is no left or right margin for printing.","""volle Breite"" bedeutet, dass das Logo über die komplette Seite von oben links bis zum rechten Rand gezogen wird. Es verbleibt kein Druckrand."
"Show Order ID as Barcode","Bestellnummer als Barcode anzeigen."
"Prints the order ID as a barcode on the right hand side.","Zeigt die Bestellnummer als Barcode auf der rechten Seite an."
"Left: Customer address left, Invoice details right. Right: Invoice details left, Customer address right.","Links: Kundenadresse links, Rechnungsdetails rechts. Rechts: Rechnungsdetails links, Kundenadresse rechts"
"Show address above shipping/invoice address","Zeige Adresse über Empfängeradresse"
"Fonts for PDF Creation","Schriftarten für PDF Erstellung"
"You can upload your own fonts (*.ttf, *.otf) instead of using Zends Helvetica","Sie können eigene Schriften (*.ttf, *.otf) hochladen, statt Zends Helvetica zu benutzen."
"Registered seat:","Sitz:"
"Register court:","Amtsgericht:"

**Comment by sprankhub** [comment]
@eddy2009 simply edit the file with a simple text editor and not with Excel or something alike.

**Comment by eddy2009** [comment]
I stand on the "Schlauch" :-)
I change my FireGento_Pdf.csv (see above).
Which line i should change please?

**Comment by eddy2009** [comment]
or I need to change the general language.csv

**Comment by sprankhub** [comment]
My previous post says it all: https://github.com/firegento/firegento-pdf/issues/218#issuecomment-74890964

**Comment by eddy2009** [comment]
now I understand nothing more ... please could you write me it step by step

**Comment by eddy2009** [comment]
:-)

**Comment by eddy2009** [comment]
i need only "19%"...

**Comment by Schrank** [comment]
Hi eddy, we are sorry but we don't have free support here. We love to maintain our module, but not your store. If you need help, you are free to hire @sprankhub which sounds like a small issue.

**Comment by eddy2009** [comment]
ok. sorry.
One question: Where can i change the receiver adress... i want delete the telephonenummer.

thanks

**Comment by Schrank** [comment]
You can change the address tempalte under Customer > Adress Template > PDF

```
                    {{depend company}}{{var company}}|{{/depend}}
                    {{depend prefix}}{{var prefix}} {{/depend}}{{var firstname}} {{depend middlename}}{{var middlename}} {{/depend}}{{var lastname}}{{depend suffix}} {{var suffix}}{{/depend}}|
                    {{if street1}}{{var street1}}|
                    {{/if}}
                    {{depend street2}}{{var street2}}|{{/depend}}
                    {{depend street3}}{{var street3}}|{{/depend}}
                    {{depend street4}}{{var street4}}|{{/depend}}
                    {{if postcode}}{{var postcode}} {{/if}}{{if city}}{{var city}}{{/if}}|
                    {{var country}}|
                    {{depend telephone}}Tel: {{var telephone}}{{/depend}}|
                    {{depend fax}}<br/>Fax: {{var fax}}{{/depend}}|
```

Just remove `{{depend telephone}}Tel: {{var telephone}}{{/depend}}|`

**Comment by Schrank** [comment]
And no need to be sorry. Asking is ok :-)

**Comment by eddy2009** [comment]
thank you :-)

**Comment by eddy2009** [comment]
Hello again,
der @sprankhub kann mir leider nicht weiterhelfen, weil er keine Zeit hat...
Ich frage ihn noch mal, dass er zumindest das Problem mit der 19% löst.

**Comment by Schrank** [comment]
I have entries in the following files:

    app/design/adminhtml/default/default/locale/de_DE/translate.csv
    "Mage_Sales::Tax","enth. MwSt. (19%)"

    app/design/frontend/rwd/ikono/locale/de_DE/translate.csv
    "Grand Total","Gesamtsumme<br /><span class=""checkout-tax-info"">inkl. 19% MwSt.</span>"


HTH

**Comment by eddy2009** [comment]
i need it for the frontend and pdf.
At first I did not find "Mage_Sales:"

and second i did not find the folder app/design/frontend/rwd/ikono/locale/de_DE/translate.csv
"ikono???" 


this is my app/design/adminhtml/default/default/locale/de_DE/translate.csv

"Credit Card Type","Kreditkartentyp"
"Add New User","Neuer Benutzer"
"Items that you don","Artikel, die Sie nicht"
"State/Province","Bundesland"
"Magento Commerce - Administrative Panel","Magento Commerce - Administrationsbereich"
"3 stars","3 Sterne"
"Credit Memo Date","Datum der Rechnungskorrektur"
"Double click on a group to rename it","Klicken Sie doppelt auf eine Gruppe, um diese umzubenennen"
"Rating Not Available","Bewertung nicht verfügbar"
"Gift Certificate","Gutschein"
"Assigned Answers","Zugewiesene Antworten"
"Fax","Fax"
"Magento Admin","Magento Administration"
"Newsletter Message Preview","Newsletter Nachrichtenvorschau"
"4 stars","4 Sterne"
"Company","Firma"
"Invoice Date","Rechnungsdatum"
"Qty Returned","Anzahl zurückgeschickt"
"Add New Customer Group","Neue Kundengruppe"
"Visitors","Besucher"
"Shipping Method","Versandart"
"Subtotal","Zwischensumme"
"5 stars","5 Sterne"
"Choose Store","Bitte Store wählen"
"Import Tax Rates","Steuersätze importieren"
"Roles","Gruppenberechtigungen"
"If you do not specify an option value for a store then the default value will be used.","Wenn Sie für einen Store keinen Optionswert für einen Store festlegen, wird der Standardwert verwendet."
"Shipping","Versand"
"Select from existing customer addresses:","Aus bestehenden Kundenadressen:"
"Products","Artikel"
"Edit User ","Benutzer bearbeiten"
"Item Status","Artikelstatus"
"Set as default billing address","Als Standard-Rechnungsadresse verwenden"
"Position","Position"
"Items Ordered","Bestellte Artikel"
"Fixed","Festkosten"
"%s","%s"
"Same as Billing Address","wie Rechnungsanschrift"
"Product In Stores","Artikel in Stores"
"Working...","Bearbeitung läuft …"
"Apply coupon code","Rabattcode einlösen"
"per page","pro Seite"
"Tax","Steuer"
"Telephone","Telefon"
"Wishlist","Wunschzettel"
"Magento","Magento"
"Expiration Date","Ablaufdatum"
"Add New Class","Neue Steuerklasse"
"Super product attributes configuration","Super-Artikel Attributkonfiguration"
"Previus page","Vorherige Seite"
"Something went wrong...","Ein Fehler ist aufgetreten …"
"Lifetime Sales","Gesamteinnahmen"
"SKU","Artikelnummer"
"Log Out","Abmelden"
"Failed","fehlgeschlagen"
"Billing Address","Rechnungsadresse"
"Log into Magento Admin Page","Anmeldung zum Administrationsbereich"
"Invoice Status","Rechnungsstatus"
"CC Type","Kreditkartentyp"
"Percentage","Prozentsatz"
"Are you sure?","Sind Sie sicher?"
"Email","E-Mail"
"Customer Group:","Kundengruppe:"
"Option","Option"
"Primary Billing Address","Standard Rechnungsadresse"
"Create Backup","Sicherung erstellen"
"Manage Options (values for your attribute)","Optionen verwalten (Werte für Ihre Attribute)"
"Total Due","Gesamtbetrag fällig"
"Copyright 2007","Urheberrecht 2007"
"Newsletter Subscribers","Newsletter Abonnenten"
"CC Number","Kreditkartennummer"
"Add New Tax Rate","Neuer Steuersatz"
"Product Name","Artikelname"
"Country","Land"
"Purchase order number","Auftragsnummer"
"Date and Time","Datum und Zeit"
"Categories","Kategorien"
"Qty Cancelled","Anzahl Storniert"
"Card Verification Number","Kartenprüfennummer"
"Order Date","Bestelldatum"
"This tab contains invalid data. Please correct before saving.","Dieses Tab enthält ungültige Daten. Bitte beheben Sie dieses Problem bevor Sie speichern."
"Customer Balance","Kontostand"
"Update Qty","Anzahl aktualisieren"
"Customer Groups","Kundengruppen"
"Export to","Export nach"
"configuration","Konfiguration"
"Sorry, no quotes are available for this order at this time.","Entschuldigung, momentan gibt es keine Angebote für diese Bestellung."
"Options","Optionen"
"Attribute Name","Attributname"
"Total <strong>%d</strong> records found","Insgesamt <strong>%s</strong> Einträge gefunden"
"Comment","Kommentar"
"Set as default shipping address","Als Standard-Versandadresse verwenden"
"Last Name","Nachname"
"of","von"
"Newsletter Problem Reports","Newsletter Problemberichte"
"Sales Statistics","Verkaufsstatistik"
"Qty To Return","Anzahl für Rücksendung"
"New Customer Address","Neue Kundenanschrift"
"Roles Resources","Gruppenberechtigung Zugriffsrechte"
"Zip/Post Code","Postleitzahl"
"Order Status","Bestell-Status"
"Store","Store"
"Product Categories","Artikelkategorien"
"Online Customers","Kunden online"
"Next page","Nächste Seite"
"Items Shipped","Versandte Artikel"
"Unassigned Attributes","Nicht zugewiesene Attribute"
"Not Charged Yet","Noch nicht belastet"
"This group contains system attributes.\nPlease, move system attributes to another group and try again.","Diese Gruppe enthält Systemattribute. Bitte verschieben Sie die Systemattribute in eine andere Gruppe und versuchen Sie es noch einmal."
"copy data from","Daten kopieren von"
"Add","Hinzufügen"
"Total Payed","Gesamt gezahlt"
"Shopping Cart","Warenkorb"
"Order History","Bestellverlauf"
"Empty","Leer"
"Unable to complete request. Please, try again later.","Die Anfrage konnte nicht verarbeitet werden. Bitte versuchen Sie es später noch einmal."
"Customers","Kunden"
"Customer does not have any addresses","Der Kunde hat noch keine Adressen angelegt"
"Add New Role","Neue Gruppenberechtigung"
"Street Address","Straße"
"Are You Sure?","Sind Sie sicher?"
"Shipping Address","Versandadresse"
"Paid","Bezahlt"
"Page","Seite"
"Discount","Rabatt"
"Set root category for this store in","Rootkategorie für diesen Store in"
"Groups","Gruppen"
"View","Ansicht"
"Qty Ordered","Bestellte Menge"
"Global Record Search","Globale Suche"
"Card Number","Kartennummer"
"PO Number","Auftragsnummer"
"Grand Total","Gesamtsumme"
"Please select one or more attributes.","Bitte wählen Sie ein oder mehrere Attribut(e)"
"Dashboard","Übersicht"
"Are you sure you want to do this?","Sind Sie sicher, dass Sie das tun möchten?"
"Please add one or more options","Bitte fügen Sie mindestens eine Option hinzu"
"Role Users","Gruppenberechtigung Benutzer"
"Add New Tax Rule","Neue Steuerregel"
"Subscribe to newsletter","Für Newsletter anmelden"
"Dashboard Control","Übersicht"
"Default Shipping","Standard Versand"
"Qty","Menge"
"Add to Queue","Zur Warteschlange hinzufügen"
"Average Sale","Durchschnittlicher Verkauf"
"Cancel","Abbrechen"
"All stores","Alle Stores"
"Personal Information","Persönliche Informationen"
"City","Stadt"
"Export Tax Rates","Steuersätze exportieren"
"1 star","1 Stern"
"Current Configuration Scope","Aktueller Konfig.-Bereich"
"Add New Template","Neue Vorlage"
"Move to:","Verschieben nach:"
"First Name","Vorname"
"Change Order Status","Bestellstatus ändern"
"Are you sure you want to delete this address?","Soll diese Adresse wirklich gelöscht werden?"
"Are you sure you want to do it?","Sind Sie sicher, dass Sie das tun möchten?"
"Add to Order","Zur Bestellung hinzufügen"
"Product ID","Artikel-ID"
"Payment Method","Zahlungsart"
"What is this?","Was ist das?"
"Users","Benutzer"
"Customer Addresses","Kundenanschrift"
"Qty Backordered","Nachbestellte Menge"
"You can not remove system attribute from this set.","Sie können Systemattribute nicht aus diesem Attributset entfernen."
"Price","Preis"
"Who","Wer"
"Rating Not Alvailable","Bewertung nicht verfügbar"
"Order Comment","Bestellkommentar"
"Edit Role","Gruppenberechtigung bearbeiten"
"Tax Rates Import / Export","Steuersätze importieren/exportieren"
"Magento Logo","Magento Logo"
"A name is required","Ein Name wird benötigt"
"Assigned options","Zugewiesene Optionen"
"Please Enter New Group Name","Bitte geben Sie den Gruppennamen an"
"Name","Name"
"Email Preview","E-Mail-Vorschau"
"Newsletter Queue","Newsletter Warteschlange"
"Remove","Entfernen"
"Last Log In:","Letzte Anmeldung:"
"Logged in as <strong>%s</strong>","Sie sind angemeldet als <strong>%s</strong>"
"Name on Card","Karteninhaber"
"All Stores","Alle Stores"
"Send comment to customer","Kommentar an Kunden senden"
"Account Created on:","Kundenkonto angelegt am:"
"Backups Control","Datensicherungskontrolle"
"Add New Address","Neue Adresse"
"Account Created in:","Kundenkonto angelegt in:"
"Default Billing","Standardrechnung"
"Manage Titles (Size, Color, etc.)","Bezeichnungen verwalten (Größe, Farbe, etc.)"
"Please confirm site switching. All data not saved will be lost.","Bitte bestätigen Sie, dass Sie die Seite wechseln möchten. Dadurch gehen alle nicht gespeicherten Informationen verloren!"
"Please select from each ratings above","Bitte wählen Sie einen Wert für jede Bewertung"
"Qty Shipped","Versandte Menge"
"Are you sure you want to cancel add this address?","Sind Sie sicher, dass abbrechen möchten?"
"The information in this tab has been changed.","Die Informationen in diesem Tab wurden geändert."
"2 stars","2 Sterne"
"Apply","Anwenden"
"Total","Gesamt"
"User roles","Benutzergruppen"
"Wishlist Report","Wunschzettelbericht"

**Comment by eddy2009** [comment]
or the settings in the backend are wrong???
In frontend is displayed: Gesamtsumme (inkl. Steuern). This line I need to find it. And than this Gesamtsumme (inkl. Steuern) changend in Gesamtsumme (inkl. 19% MwSt.).

**Comment by eddy2009** [comment]
app/design/adminhtml/default/default/locale/de_DE/translate.csv
If I delete the folder completely change in the pdf only the following:
"Steuer" in "Ust."
"Menge" in "Anzahl"
then nothing.

**Comment by Schrank** [comment]
I edited the comment twice, sorry for confusion.

This file needs to be in your theme. if it doesn't exist, create it

app/design/frontend/<package>/<theme>/locale/de_DE/translate.csv
"Grand Total","Gesamtsumme<br /><span class=""checkout-tax-info"">inkl. 19% MwSt.</span>"

**Comment by eddy2009** [comment]
Yeeeeees!
The invoice pdf is perfect
Now i try it for frontend...

**Comment by eddy2009** [comment]
whic folder is the right for the frontend?

**Comment by sprankhub** [comment]
Please do not use this bug tracker as a support forum or help center or whatever.
