### ISSUE TITLE
Copy of original bill

### ISSUE THREAD

**Issue by Jamal23** [firegento/firegento-pdf#223]
Hi there,
first, you have done a good job.

How is it possible to get a copy of the bill, with marker "Copy".

For example: When i create the bill and want to print the bill, the pdf should contain 2 or 3 versions of the bill, but the 2nd and 3rd version should contain the word "Copy" in it.

Best regards.

**Comment by Schrank** [comment]
I don't think this is easily possible, but you can implement your own engine, just generate the same invoice three times and place a transparent PNG over it.
