### ISSUE TITLE
Update Translation Files

### ISSUE THREAD

**Issue by sprankhub** [firegento/firegento-pdf#225]
Some strings are not in the translation files. Check that and add all strings to the translation files.

**Comment by Schrank** [comment]
Here all XML files are missing, I only checked all the __ ... So whoever is interested, please check the XML files and update the translations

**Comment by sprankhub** [comment]
This may be of help: https://github.com/ericthehacker/magento-untranslatedstrings / http://www.classyllama.com/blog/magento-translation-step-zero-what-must-be-translated
