### ISSUE TITLE
Payment method: Margin right act wrong

### ISSUE THREAD

**Issue by alexrip** [firegento/firegento-pdf#226]
Hi there,

I added the payment method to the invoice layout (header block), but its not getting displayed correctly --> margin right does not act normally. The payment method is not aligned totally to the right as all the other elements. Instead its somehow displayed in the "middle".

What can I do to change that?

Thanks!

**Comment by sprankhub** [comment]
Do you use the latest version? Please provide a screenshot and tell us which payment method it is.

**Comment by alexrip** [comment]
Thanks for your quick reply! I attached a screenshot and we use version 1.3.0.
![capturfiles](https://cloud.githubusercontent.com/assets/7351997/6651625/0a3cf3f6-ca4b-11e4-88e5-be274e743575.png)

I think there is no difference between the payment methods. I only checked two yet.

**Comment by sprankhub** [comment]
Thanks for the report. Should be fixed with the latest commit in the development branch.

**Comment by alexrip** [comment]
OK thanks, I will update that :)
