### ISSUE TITLE
Serial Codes on PDF Invoice

### ISSUE THREAD

**Issue by Megabooth** [firegento/firegento-pdf#229]
Hallo,

I use the firegnto setup and pdf extension for my store.
Mainly for warranty cases, we use serial codes (extension link: http://www.magentocommerce.com/magento-connect/serial-codes.html ).
I would like to let our customers know, which serial codes we issued for his ordered products and print them on the invoice.

For the standard pdf invoice, provided by Magento, it works fine, but for our smooth custom pdf invoice (created with firegento), the code additional code added in the default.php file, doesn't work.

The additional code was provided by the developer and should be added to the file after the lines with the product name (the serial codes are printed directly under the name of the product in extra lines) :
```php 
        // draw Product name
        $lines[0][] = array(
            'text' => Mage::helper('core/string')->str_split($item->getName(), 40, true, true),
            'feed' => $pdf->margin['left'] + 130,
            'font_size' => $fontSize
        );
		
// Start Serial Codes Modification
$product = Mage::getModel('catalog/product')->setStoreId($order->getStoreId())->load($item->getProductId());
$sc_item = Mage::getModel('sales/order')->load($order->getEntityId())->getItemById($item->getOrderItemId());
$codetype = $sc_item->getSerialCodeType();
$codes = explode("\n",$sc_item->getSerialCodes());
$codeids = array_pad(explode(',',$sc_item->getSerialCodeIds()),count($codes),'');
if ($codes[0]) {
    for ($i=0; $i<count($codes); $i++) {
        if (Mage::getSingleton('serialcodes/serialcodes')->hidePendingCodes($order, $sc_item, $product, $codeids[$i], $i)) {
            $codes[$i] = Mage::helper('serialcodes')->__('Issued when payment received.');
        }
        $lines[0][0]['text'][] = '     '.$codetype.': '.$codes[$i];
    }
}
// End Serial Codes Modification
```
as I mentioned, for the Standard pdf files (path is `app\code\local\Mage\Sales\Model\Order\Pdf\Items\Invoice\Default.php`), it works:
![unbenannt](https://cloud.githubusercontent.com/assets/11852425/7044356/ed2cb9d4-ddf2-11e4-833e-2af8b53b3116.PNG)

Do you have any ideas concerning my problem?
I would be grateful for any help. Thanks a lot in advance!
Oliver

**Comment by Schrank** [comment]
Did you try to add a whole line block definition?

` $lines[0][0]['text'][] = '     '.$codetype.': '.$codes[$i];` is a little less.

You should try:
        $lines[0][] = array(
            'text' => '.$codetype.': '.$codes[$i],
            'feed' => $pdf->margin['left'] + 130,
            'font_size' => $fontSize
        );

But because this is no bug and an open source project, we can't offer free support here. You are invited to ask Simon or me for paid support.
