### ISSUE TITLE
Add Tax/VAT number to invoice/shipment/creditmemo print.

### ISSUE THREAD

**Issue by AlexandrDanilov** [firegento/firegento-pdf#230]
I have added the Tax/VAT number to invoice/shipment/creditmemo print. Many people need it.
How can I pull the changes here?

**Comment by Schrank** [comment]
Isn'T the VAT ID an address field, so you can just add it, changing the address template?

**Comment by sprankhub** [comment]
I think the same as @Schrank. Where exactly did you add the VAT ID @AlexandrDanilov?

**Comment by AlexandrDanilov** [comment]
I have added it in PDF print. 
app\code\community\FireGento\Pdf\Model\Engine\Abstract.php in insertHeader() method between Customer Number and Customer IP. 
And also I have added the options in system.xml, so people can enable/disable the TAX/VAT output.
I just want to pull the changes to github to development branch, but not have the permissions. )

**Comment by sprankhub** [comment]
Just to make sure: You mean the customer VAT ID, right? Not the one from the store owner? Then it may be interesting, because having it in the address section is not really convenient. What do you think @Schrank?

@AlexandrDanilov You can learn [how to create pull requests here](https://help.github.com/articles/using-pull-requests/).

**Comment by AlexandrDanilov** [comment]
Yes, I mean the customer VAT ID.
Thank you for the link. )

**Comment by Schrank** [comment]
To add a PR you have to fork the project, add your code, commit and push it and then make a PR from your repo.

I still think we don't need it and address is enough. But if you two think it is worth it, let'S add it :)

**Comment by AlexandrDanilov** [comment]
Some store owners want to print the TAX/VAT number in PDF header. So we should add this option, I think. :) 
Thank you guys for your detailed answers. Looks like I got it. :)

**Comment by sprankhub** [comment]
Thanks for your contribution!
