### ISSUE TITLE
Crash in app/code/community/FireGento/Pdf/Helper/Data.php

### ISSUE THREAD

**Issue by winkelsdorf** [firegento/firegento-pdf#232]
When trying to print multiple invoices, firegento-pdf crashes.

```code
Fatal error: Call to a member function getCreatedAt() on a non-object in /Users/winkelsdorf/Sites/magento.dev/app/code/community/FireGento/Pdf/Helper/Data.php on line 321
```

Looks like it's related to the strftime parsing.

Config "Filename Export Pattern for Multiple Documents" is set to "magento.dev %Y%m%d-%H%M%S".

Edit: Using latest development branch with Composer/Satis "firegento/pdf": "dev-development".

**Comment by Schrank** [comment]
Which version are you using? Never had this problem. Will try to reproduce it.

**Comment by sprankhub** [comment]
This is kind of a new feature, so it may be a new problem. Will have a look at the code later.

**Comment by Schrank** [comment]
I can't reproduce this. I'm setting 

> "Filename Export Pattern for Multiple Documents" to "magento.dev %Y%m%d-%H%M%S"

Then I export three orders and get one PDF with three invoices in it. Anything I'm making "wrong"?

**Comment by sprankhub** [comment]
I could reproduce and will fix asap.

**Comment by Schrank** [comment]
(y)

**Comment by sprankhub** [comment]
@winkelsdorf could you please check with the latest dev branch again and confirm that it is fixed?

**Comment by winkelsdorf** [comment]
@sprankhub Yes, I can confirm that  https://github.com/firegento/firegento-pdf/commit/389430231c721b7edd10cf312ae91a7b66427fc7 fixes the bug. Tested "Print All" for Orders with single and multiple Credit Memos.

Thank you very much!
