### ISSUE TITLE
Footer column widths should allow for longer websites an emails

### ISSUE THREAD

**Issue by dakira** [firegento/firegento-pdf#236]
This happens with the current *HEAD*.

![breaking](https://cloud.githubusercontent.com/assets/576555/7472729/d5eac61e-f335-11e4-8f88-874f1e716b0d.png)

In the best case the optimal widths should be calculated.

**Comment by Schrank** [comment]
it is only broken by a space :)

**Comment by dakira** [comment]
@Schrank the columns are "soft-wrapped" which works if you have multiple words. With one word (as in websites and emails) the soft-wrapping causes a line-break.

**Comment by sprankhub** [comment]
Could you please have a look at the solution above? Do you think this is a good idea? Does it work for you?

Currently, we only break lines on whitespaces. Now we also break lines on dashes. I think this is the way to go.

**Comment by sprankhub** [comment]
I merged the branch into the development branch and assume this is fixed.
