### ISSUE TITLE
Wrong Tax in PDF while Confirmation mail is correct

### ISSUE THREAD

**Issue by winkelsdorf** [firegento/firegento-pdf#237]
Using magento 1.9.1.0 dev test setup with mageSetup & firegento pdf (both latest from GH).

Tax calculation in magento is correct, even the Invoice Mail sent by magento is correct. But the generated invoice pdf is not.

I am using Phoenix_CashOnDelivery to add a fixed amount to Cash On Delivery Payment Option and limit Cash On Delivery to selected Shipping Countries.

Backend Calculation is also correct, it's just the firegento pdf:

![screen shot 2015-05-07 at 15 51 29](https://cloud.githubusercontent.com/assets/1413291/7516640/f624ad4a-f4d0-11e4-84ac-53199d22de08.png)
![screen shot 2015-05-07 at 15 51 36](https://cloud.githubusercontent.com/assets/1413291/7516643/f7b487c0-f4d0-11e4-80b4-e3e5c5366d2d.png)

**Comment by winkelsdorf** [comment]
Correcting this report, the tax in the Invoice Table on the Backend is also not correct:

![screen shot 2015-05-07 at 15 55 51](https://cloud.githubusercontent.com/assets/1413291/7516755/9b415e9a-f4d1-11e4-892e-51485f025111.png)

Reported here too:
https://github.com/PHOENIX-MEDIA/Magento-CashOnDelivery/issues/23

**Comment by sprankhub** [comment]
Thanks for the detailed report! We should simply show the same values as in the backend. If this is the case, as you said, all is good from our side. If they are not correct in the backend, it is a Magento / CashOnDelivery bug.

**Comment by winkelsdorf** [comment]
Agreed, anyway thanks for having a look!
