### ISSUE TITLE
Delete "Steuer" from invoice pdf

### ISSUE THREAD

**Issue by Tronicpixel** [firegento/firegento-pdf#238]
hi,

how i can delete the "steuer" and add some text to the invoice. i need this for smallbuisness "Kleingewerbe". you see on the picture. i have to add the text and this little star to the price.

![tax](https://cloud.githubusercontent.com/assets/12382483/7554873/5b8fd8a2-f739-11e4-899f-3c6fbd22430b.jpg)

**Comment by sprankhub** [comment]
In the configuration, you can drag and drop the tax amount to the fields which should not be printed:

![image](https://cloud.githubusercontent.com/assets/930199/7555022/0dca1f78-f73f-11e4-8336-248c7b5ae394.png)

You can also add a note in the configuration:

![image](https://cloud.githubusercontent.com/assets/930199/7555027/21012fe6-f73f-11e4-947c-dbfbd85356d7.png)

Adding a star or placing the text at another position requires custom coding, e.g. [writing a custom engine](https://github.com/firegento/firegento-pdf/wiki/FAQs#i-do-not-like-the-standard-engines---how-can-i-write-my-own-engine).
