### ISSUE TITLE
Cannot make this extension work

### ISSUE THREAD

**Issue by PeteW1959** [firegento/firegento-pdf#239]
I installed this extension to do one thing, add a note to the packing slip.

Installation went well, and the configuration menu is available.

However changes made in the packing slip section make no difference at all. I have entered text in the 'Notes' box, and set print order number as a barcode, but the packing slip is exactly the same as native Magento.

Is there something else I need to do to make this extension active?

**Comment by Schrank** [comment]
You have to choose the engine. Theoretically this is done automatically in newer versions, but make sure, the `PDF Engine` is set to `FireGento Standard` and it is not `Magento Standard`.

Second thing which comes into my mind is to clear the config cache.

And third: You have some extension installed which rewrites the `sales/order_pdf_shipment` too and the first letter of the module name comes after `F` in the alphabet...

**Comment by sprankhub** [comment]
Feel free to reopen if this does not solve your issue.

**Comment by PeteW1959** [comment]
Thanks for the prompt reply. The only options I have for the engine are Standard Magento or Standard Germany.

**Comment by sprankhub** [comment]
Use "Standard Germany".

**Comment by PeteW1959** [comment]
Brilliant, thank you! Does exactly what I need. Just one small criticism, some documentation would help!

**Comment by Schrank** [comment]
Some documentation is in the docs folder and here: https://github.com/firegento/firegento-pdf/wiki/FAQs

And your problem should be solved in newer releases: https://github.com/firegento/firegento-pdf/issues/191
