### ISSUE TITLE
Display Grand Total in Base Currency alongside GT in Currency choosen by Customer

### ISSUE THREAD

**Issue by Klopko** [firegento/firegento-pdf#242]
Is there a (simple) way that firegento lets one display the grand total in base currency alongside
the currency that the customer has choosen for his purchase?

**Comment by sprankhub** [comment]
No simple way, no. I think in this case it is not really clear which exchange rate would have to be taken...

Anyway, you can implement that via a [custom engine](https://github.com/firegento/firegento-pdf/wiki/FAQs#i-do-not-like-the-standard-engines---how-can-i-write-my-own-engine).

**Comment by Schrank** [comment]
I think it can be even enough to add it via a note. And you don't need an exchange rate, because magento already saves base grand total and normal grand total.

**Comment by Klopko** [comment]
Thanks for you comments. How can I add it to the note field? Is there a variable that I could insert there which will pull the GT base from the database?

**Comment by sprankhub** [comment]
No, it is not THAT easy :) But the advantage of adding it as a note is that you can simply [use an observer](https://github.com/firegento/firegento-pdf/wiki/FAQs#how-can-i-add-notes-to-the-pdfs-programmatically).
