### ISSUE TITLE
Error print multiple shippment, firegento-pdf crashes.

### ISSUE THREAD

**Issue by smk2002** [firegento/firegento-pdf#249]
When trying to print multiple shippment (or) invoice, firegento-pdf crashes.

First, I got this error
> Fatal error: Call to a member function getCreatedAt() on a non-object in

So i follow with this link
> [~BUGFIX]  https://github.com/firegento/firegento-pdf/commit/389430231c721b7edd10cf312ae91a7b66427fc7

After that  I try to click to print all invoice. It's ok for 1 invoice and then I have two shipments so i try to print all shipments.  but i got error.

> Fatal error: Call to undefined method FireGento_Pdf_Helper_Data::getExportFilenameForMultipleDocuments() in /community/FireGento/Pdf/controllers/Sales/OrderController.php on line 116

my version is 1.3.0 (latest version from magento commerence).

This is my line no. 116 code
>  $filename = Mage::helper('firegento_pdf')->getExportFilenameForMultipleDocuments($type);

Please let me know, how can i solve it? Thanks

**Comment by Schrank** [comment]
Please update to the latest version from this repo and report back if it still fails.

**Comment by smk2002** [comment]
If i try to download 2 version in here. 1) firegento-pdf-master and 2) firegento-pdf-development . First, i try to update master version but also not ok for 1 invoice & 2 shipment.. 
> Fatal error: Call to a member function getCreatedAt() on a non-object in

Second, i try to update development version, 1 invoice is ok but 2 shipment are not ok.
> Fatal error: Call to undefined method FireGento_Pdf_Helper_Data::getExportFilenameForMultipleDocuments() in /community/FireGento/Pdf/controllers/Sales/OrderController.php on line 116

all are same previous error.... thanks

**Comment by sprankhub** [comment]
This sounds very strange. The method `FireGento_Pdf_Helper_Data::getExportFilenameForMultipleDocuments` definitely exists in the current development branch, so I guess there is something wrong on your side. But anyway, just to double check: Where exactly do you try to print the invoices/shipments?

**Comment by smk2002** [comment]
I'm trying to print in login user my account page.. 

btw, i also try to test & update for both version (Developer/maseter). This one only updated and try it.
> app\code\community\FireGento\Pdf\controllers\Sales\OrderController.php

I'm not updated everything because some layout is a bit change.

**Comment by sprankhub** [comment]
I do not fully understand your comment. Of course you have to update ALL files of the extension. Did you do that?

**Comment by smk2002** [comment]
now, i not update all, because some files is a bit change layout. such as 
> app\code\community\FireGento\Pdf\Model\Items\Default.php
> app\code\community\FireGento\Pdf\Model\Engine\

**Comment by sprankhub** [comment]
So that the extension fully works, you have to update all files. You do not need to edit core files to do layout changes. Have a look at the [FAQs](https://github.com/firegento/firegento-pdf/wiki/FAQs) to see how you can properly change the layout.

**Comment by sprankhub** [comment]
Just checked with the latest dev branch and can confirm that this works without any issues.

**Comment by smk2002** [comment]
Oh.. it is working after i try to re-upload 
> firegento-pdf-development\src\app

So, my edit core files is wrong.. thank your help..
