### ISSUE TITLE
Wechselkurse anzeigen / Basiswährung und Fremdwährung auf Rechnung

### ISSUE THREAD

**Issue by jniebergall** [firegento/firegento-pdf#251]
Hi,

ist es möglich den Wechselkurs auf der Rechnung auszugeben oder die Basiswährung sowie den Umrechnungsbetrag in Fremdwährung auszugeben?

Danke im voraus.

Grüße
Jonas

--ENGLISH--
Is it possible to display exchange rates or the base currency with the associated foreign currency on the invoice?

**Comment by Schrank** [comment]
Hi Jonas,

das geht aktuell nicht. Du kannst dir dazu eine eigene Engine schreiben oder es in die Notizen mit schreiben, wie im Wiki angegeben: https://github.com/firegento/firegento-pdf/wiki/FAQs#how-can-i-add-notes-to-the-pdfs

Man kann mal darüber nachdenken es in die Tabelle mit aufzunehmen, aber ich denke, dass das dann ziemlich unübersichtlich wird...

**Comment by jniebergall** [comment]
Hi Fabian,

danke für die schnelle Antwort !

**Comment by Schrank** [comment]
Damn, please use english :D You can think about expanding the list of things, we can add to the table, shouldn't bee soo hard.

**Comment by Schrank** [comment]
I think this can't be implemented, because the exchange rate changes, therefore the prices change between the creation of the order and creation of the invoice.

I wouldn't implement this, because it is a big source of problems.
