### ISSUE TITLE
Product name formatting error in pdf invoice

### ISSUE THREAD

**Issue by dalius13** [firegento/firegento-pdf#254]
Hello,
When product name is long, it comes onto next field and covers it. So contents are mixed and not readable.
Solution:
In file: /app/code/community/FireGento/Pdf/Model/Items/Default.php
the row no. 72 is:
72            'text' => Mage::helper('core/string')->str_split($item->getName(), 40, true, true),
must be:
72            'text' => Mage::helper('core/string')->str_split($item->getName(), 35, true, true),
because in Magento base default for product name function str_split() have value=35 too.

Best Regards,
dalius13

**Comment by sprankhub** [comment]
Thanks for the report. I just checked that and cannot reproduce it at all:
![image](https://cloud.githubusercontent.com/assets/930199/8871065/d175b386-31f2-11e5-9ae6-1d5bfeced542.png)

Could you share a screenshot of the invoice and a screenshot of your settings?

**Comment by dalius13** [comment]
I send all information in attached files:
Rech_545_value40.jpg - Invoice with str_split() value of 40 - with
formatting error
Rech_545_value35.jpg - same invoice with str_split() value of 35 - formats
correctly

I have noted, that this problem exists with str_split() value of 35 too. It
can you see in attachment Rech_15_value35.jpg.
In all cases formatting is correct, if I use "Standard Magento" PDF Engine.
So str_split() value of 35 doesn't solve this problem generally and. Maybe
it is problem with word wrapping.

Best Regards,

Dalius Juodvirsis

**Comment by Schrank** [comment]
Hi dalius,

You can't attach files to mails to github, can you please add them to the tracker? Thanks!

**Comment by dalius13** [comment]
![rech_15_value35](https://cloud.githubusercontent.com/assets/12410025/8893219/c0ced0f2-3388-11e5-8eaf-1925eb0886a1.jpg)
![rech_545_value35](https://cloud.githubusercontent.com/assets/12410025/8893220/c0d1bc72-3388-11e5-92db-a25d6b706e61.jpg)
![rech_545_value40](https://cloud.githubusercontent.com/assets/12410025/8893221/c0d4b6b6-3388-11e5-9b92-2661b4a162f4.jpg)
![screenshot1](https://cloud.githubusercontent.com/assets/12410025/8893222/c0d78d00-3388-11e5-80f9-318e9d8148d4.png)
![screenshot2](https://cloud.githubusercontent.com/assets/12410025/8893223/c0ddff14-3388-11e5-80a8-34fed9590778.png)
![screenshot3](https://cloud.githubusercontent.com/assets/12410025/8893224/c0e237a0-3388-11e5-968a-e3abd550a033.png)

**Comment by sprankhub** [comment]
I just checked it with your settings and your product name. I cannot reproduce it:
![image](https://cloud.githubusercontent.com/assets/930199/8894078/1d453576-33aa-11e5-9cb5-955af9963c86.png)

Sorry... Maybe you want to check with the current development branch...

**Comment by dalius13** [comment]
From today and until August 9th I'm in vacation.
I'll continue from August 10th.
