### ISSUE TITLE
Logo and customer IP

### ISSUE THREAD

**Issue by HeroicTales** [firegento/firegento-pdf#255]
Hello,

A few weeks ago I updated my 1.7magento to 1.9.2 and I came across an old and a new issue.
The old one was that I don't want customer IP address appears on the packing slip/invoice.
The new one is that it seems I can't put my logo on the same packing slip/invoice.

Can anybody help?

Thank you.

**Comment by Schrank** [comment]
You can hide the customer ip in the settings:

    Sales > Sales > General > Hide Customer IP

What exactly is your problem with the logo? May you add a screenshot of your settings and the invoice?

**Comment by HeroicTales** [comment]
Thank you. The IP is done.

The problem with the logo that it doesn't show on the packing slip/invoice.

![printscreen 3](https://cloud.githubusercontent.com/assets/13573111/8986157/226a089a-36db-11e5-8c8a-1f13c7e78b59.jpg)
![printscreen 1](https://cloud.githubusercontent.com/assets/13573111/8986169/388a8c62-36db-11e5-840b-e5ca3f72cda7.jpg)
![printscreen 2](https://cloud.githubusercontent.com/assets/13573111/8986173/3be1e59a-36db-11e5-8c60-f0dbb52c7845.jpg)

**Comment by sprankhub** [comment]
You have to upload it under System - Configuration - Sales - Invoice and Packing Slip Design

**Comment by Schrank** [comment]
![bildschirmfoto 2015-07-30 um 16 56 40](https://cloud.githubusercontent.com/assets/379680/8986340/09222f92-36dc-11e5-83c5-9f4eec6f720d.png)

**Comment by HeroicTales** [comment]
@!X* Grumble... that easy. I need a pair of glasses. Thank you.
