### ISSUE TITLE
Bundle products broken

### ISSUE THREAD

**Issue by infabo** [firegento/firegento-pdf#258]
Hi!

Can anybody confirm that bundle products are not correctly rendered in firegento-pdf invoice?
For the lines of the bundle-items it always renders the bundle-total-price instead of the bundle-item single price.
The line-total for every bundle-item line is always 0,00EUR (instead of the bundle-item-price x quantity).

How to reproduce:
Create a bundle product with some bundle items, create order, create invoice -> have a look. :)

**Comment by sprankhub** [comment]
I can confirm that. I get the following output with my test bundle product:

![image](https://cloud.githubusercontent.com/assets/930199/9443828/a73bd6f0-4a83-11e5-97f3-560a29528d42.png)

Thanks for the report!

**Comment by sprankhub** [comment]
See https://github.com/firegento/firegento-pdf/commit/4b7b831b06eba7177c7f264ed26dfe531b19fa0a. Could you please check it with the current development branch and confirm if the issue is resolved? Thanks!

**Comment by sprankhub** [comment]
I assume that this issue is fixed. Please reopen if the issue persists.

**Comment by infabo** [comment]
fixed! sry for no feedback.
