### ISSUE TITLE
Translation issue with "Tax"

### ISSUE THREAD

**Issue by mr-jingles** [firegento/firegento-pdf#261]
In FireGento_Pdf.csv "Tax" is declared as "USt." for German translation. However it is translated to "Steuer" in the totals.

**Comment by Schrank** [comment]
The totals are part of Mage_Sales (I think) and therefore `Mage_Sales.csv` is used for translation.

You can either have a local.csv in both of your themes (frontend and admin) or you change it in `Mage_Sales.csv`

**Comment by mr-jingles** [comment]
I did that for 
"Shipping & Handling","Versand"
that line worked fine, however this one didn't work:
"Tax","MwSt. 19%"
I thought someone has a solution - since the default which is declared in  FireGento_Pdf.csv also does not work. And I think at least the translation defined in the module itself should work. Don't you think that this is a bug?

**Comment by Schrank** [comment]
If this doesn't work, then one (you?) need to dig into the code and check, which "namespace" is used for the translation. If you find it, it would be great if you can tell us, so we can put it into the FAQ :)

**Comment by mr-jingles** [comment]
I tried that already - I have checked all of the translation files (where I could find the String) and changed them one by one with no luck so far.

I will double check! But the issue - I think - is still open.

**Comment by sprankhub** [comment]
I just checked that (by the way this is not exactly an issue with this extension).

You can use a custom admin theme and use the translate.csv in it. For instance add the following entry to `app/design/adminhtml/default/myadmintheme/locale/de_DE/translate.csv`:

    "Tax","MwSt. 19%"

This is translated [here](https://github.com/OpenMage/magento-mirror/blob/magento-1.9/app/code/core/Mage/Sales/Model/Order/Pdf/Total/Default.php#L53).

**Comment by mr-jingles** [comment]
@sprankhub Thank You! The issue was  within Rico Neitzel's  LanguagePack - I thought it is just translating the modules. However there is also a translate.csv file linked into the default theme of adminhtml! I created my own theme now as you suggested and it works flawlessly.

**Comment by dwdsamag** [comment]
But what happens when you have products with 7% AND 19%? 
Maybe you try **Verkäufe -> Steuern -> Steuersätze verwalten** or **SALES -> Tax -> Manage Tax Zones**

**Comment by sprankhub** [comment]
Then you can configure in the system configuration that each tax class should be shown separately.
