### ISSUE TITLE
How to remove the Tax rate on invoices? (not the name, or amount)

### ISSUE THREAD

**Issue by thetankgirl** [firegento/firegento-pdf#263]
How do I remove the tax rate ( example: 6.0000%, of 21.0000%) on the invoice pdf's (in the totals section)? Just to be clear, I want the Name and the amount to stay, I just want the rates to be gone.

**Comment by sprankhub** [comment]
This cannot be done in an easy way. You can write your own engine, rewrite the `insertTotals` method there and do some black magic like removing everything in parantheses or something like that. Have a look around this code: https://github.com/firegento/firegento-pdf/blob/development/src/app/code/community/FireGento/Pdf/Model/Engine/Abstract.php#L911-L931
