### ISSUE TITLE
Invoice Address in packingslip

### ISSUE THREAD

**Issue by kledy** [firegento/firegento-pdf#264]
Hi,
is it possible to insert the invoice address in the packingslip? In the settings I couldn't find this. Or could someone give me a hint, where I can start to implement this?

**Comment by Schrank** [comment]
It is not possible (yet?). It depends where you want to have it. I think easiest is to add it to the notes section as described here: https://github.com/firegento/firegento-pdf/wiki/FAQs#how-can-i-add-notes-to-the-pdfs

If you want to have it somewher else, you either use this: https://github.com/firegento/firegento-pdf/wiki/FAQs#how-can-i-put-some-fancy-stuff-wherever-i-want-to-without-writing-my-own-engine or you implement your own engine: https://github.com/firegento/firegento-pdf/wiki/FAQs#i-do-not-like-the-standard-engines---how-can-i-write-my-own-engine
