### ISSUE TITLE
PDF Layout, 

### ISSUE THREAD

**Issue by eddy2009** [firegento/firegento-pdf#265]
Hallo,
sorry, dass ich nicht in english schreibe, da mein englisch nicht so gut ist.
Suche seit Tagen nach einer Lösung aber leider erfolglos.

1. Ich wollte die Textgrößen ändern. Wo genau kann ich das machen? Z.Bsp. ist die Absenderzeile zu klein.
2. Das Logo ist nahe an der Absenderzeile. Ich könnte das Logo entsprechend anpassen in dem ich das jpg die untere Seite weiß lasse.
3. Und "Steuer" in "19% MwSt." umwandeln.

Danke
LG

**Comment by Schrank** [comment]
I assume you don't want to write english but you are able to understand it - if I'm wrong, please tell me, then I'll switch. And btw, this is a good place to practice english ;-)

1. should be here: https://github.com/firegento/firegento-pdf/blob/development/src/app/code/community/FireGento/Pdf/Model/Engine/Abstract.php#L227

2. I don't understand the problem? Maybe add a screenshot
3. we translate `Tax`, therefore you can just add a translate.csv in frontend and backend theme with the content:

"FireGento_Pdf::Tax","19% MwSt."

**Comment by eddy2009** [comment]
Hi,
you will maybe not believe it but I really have been learning english days on Magento platforms. :-)
Ich rede schon mit meiner Freundin jetzt auch english :-) 
Würde mich freuen, wenn Sie auf deutsch antworten.... nur das eine Mal :-)

Zunächst vielen Danke für die schnelle Antwort.

Zu 1: ich werde es versuchen.

Zu 2. Habe den Satz nicht vollendet. Das Logo ist zu nah an der Absenderadresse. Ich könnte ja bisschen tricksen, wenn ich das untere Teil vom Logo (jpg) halt weiß gestallte, also die Höhe des Logos so erstellen, dass der Inhalt sich quasi nach oben schiebt.
Oder gibt es dafür eine Code-Stelle wo ich die Abstände eingeben kann?

Zu 3: Ich kann wohl die translate.cvs, die ich mit excel öffne, nicht entsprechend editieren und hochladen. Die Änderungen sind nicht wirksam.
Oder ich ändere eine falsche cvs Datei :-) solche Fehler passieren mir schon ab und zu ;-) 
Auch im frontend bei der Preisanzeige steht nicht "19% MwSt.". Dies wollte ich per "Inliner" ändern, ging aber auch nicht.

Danke vielmals im voraus.
LG

**Comment by eddy2009** [comment]
Zu 1: worked great
Zu 2 : I still have no solution
Zu 3: I still have no solution

**Comment by sprankhub** [comment]
Denk dran, dass all deine Änderungen verloren gehen, wenn du sie direkt im Modul machst. Du solltest lieber eine eigene Engine schreiben (siehe Wiki, Fabian hatte den Link schon geposted).

2: Schau dir mal die Methode hier an https://github.com/firegento/firegento-pdf/blob/development/src/app/code/community/FireGento/Pdf/Model/Engine/Abstract.php#L393
3: Siehe https://github.com/firegento/firegento-pdf/issues/261

**Comment by eddy2009** [comment]
oooooo... sorry. Fabian hat mir eigentlich mit einem Schlag geholfen... nur ich habe es nicht gesehen :)
Danke vielmals
