### ISSUE TITLE
Hide CustomerNo. for guest orders

### ISSUE THREAD

**Issue by riker09** [firegento/firegento-pdf#268]
When `sales_pdf/invoice/show_customer_number` is enabled, but the order is a guest order, the customer number is rendered with a dash (`-`). I think it would make sense to either hide the customer number or give more information why no customer number is present. This can be as short as the hint "Guest order".

![firegento_pdf_guestorder](https://cloud.githubusercontent.com/assets/568497/10424812/a6ab6514-70d2-11e5-8856-0dfb598f860b.png)

This may optionally be configurable from the backend: "Hide customer number for guest orders" => Yes/No.

What do you think? Is this worth a PR?

**Comment by Schrank** [comment]
I like this, Simon? Maybe we just add a default config "-" where you can add whatever you want for Guest orders, then you have the ultimate choice.

btw, thanks for the PR and all your work here!

**Comment by riker09** [comment]
Nevermind the hard work. This is open source and I like to contribute.
