### ISSUE TITLE
More whitespace in address bar

### ISSUE THREAD

**Issue by riker09** [firegento/firegento-pdf#269]
The shop address is rendered awefully close to the customer address. Either some whitespace should be added here or a horizontal line that seperates the shop address from the customer address.

![firegento_pdf_address](https://cloud.githubusercontent.com/assets/568497/10424840/eccea7b8-70d2-11e5-917b-cd614072c4a7.png)

**Comment by Schrank** [comment]
I think it is good as it is now, because everything has to fit in a german window envelope and when you add the country the space is small. If you then add the phone number, I don't think there is space left to add?

**Comment by sprankhub** [comment]
@Schrank++

But we could check how it looks like with a tiny line as a separator - that should be doable...

**Comment by Schrank** [comment]
Tested in PR #276 and not merged.
