### ISSUE TITLE
IBAN overlaps Court

### ISSUE THREAD

**Issue by riker09** [firegento/firegento-pdf#270]
When both IBAN and Court imprint fields are filled out, the IBAN overlaps the later information. This might only be valid for some stores, but is annoying nevertheless.

![firegento_pdf_footer](https://cloud.githubusercontent.com/assets/568497/10424927/a5d799c2-70d3-11e5-952c-0ded3e560cfd.png)

I don't know what the preferred method of choice would be to solve this issue. Let the discussion beginn.

**Comment by Schrank** [comment]
The only way I can think of is to make everything smaller to gain more space

**Comment by Schrank** [comment]
Fixed.
