### ISSUE TITLE
Layout broken

### ISSUE THREAD

**Issue by awekas** [firegento/firegento-pdf#280]
At my Header the Layout is broken. How can i fix this?
![header](https://cloud.githubusercontent.com/assets/15277926/10710607/50dabffc-7a61-11e5-8684-f48d5cdc927b.PNG)

Thank you for your help.

**Comment by Schrank** [comment]
The problem: Your payment method is outputing too much.
Solution: Fix the payment module.

Alternative: Change `Show Payment Method`  to `Notes area`, so you have more space.
