### ISSUE TITLE
Korrekturbeleg instead of Gutschrift

### ISSUE THREAD

**Issue by gfobe** [firegento/firegento-pdf#281]
If you refund an order, since 01. July 2013 in Germany it is not correct to say "Gutschrift" because this term belongs to a VAT based money transfer (e.g. if you produce power with your solar panel and sold it). If we correct or refund an order it must be "Korrekturbeleg" or something like that to differ, that the recipient of money have not to pay taxes for this. See [Text of german lawyer](http://www.stb-kbt.de/timms-hinweise/detail/?tx_news_pi1[news]=315&tx_news_pi1[controller]=News&tx_news_pi1[action]=detail&cHash=35621bc791854c3471e12dd69700861f).
Courts defined, that it is not illegal to call a Korrekturbeleg as Gutschrift like the years ago.

We have multiple options to fix. I would be glad about feedback:
1. only rename german translation from "Gutschrift" to "Korrekturbeleg" (my suggestion)
2. also rename "Creditmemo" to "Correction of invoice" (could be perplexing developers knowing creditmemo)

**Comment by Schrank** [comment]
I would go with option 1

**Comment by gfobe** [comment]
Did anybody know about Switzerland and Austria? Can we call it Korrekturbeleg there too?

**Comment by Schrank** [comment]
Doesn't really matter (only for correcting). But (as you know 😃) they have their own translations.

**Comment by sprankhub** [comment]
Afaik, "Rechnungskorrektur" is also fine. This is used by Rico in his German translation. Hence, I strongly vote for using the same term here. @gfobe the term "Rechnungskorrektur" should also be okay, right?
