### ISSUE TITLE
Invoice Gesamt (brutto) and Zwischensumme is zero

### ISSUE THREAD

**Issue by galaxist740** [firegento/firegento-pdf#286]
Hello!

As you can see in the screenshot the "Gesamt (brutto)" is 0,00 €. "Zwischensumme" is 0,00 € too.
![bildschirmfoto 2015-11-06 um 10 17 10](https://cloud.githubusercontent.com/assets/14994366/10993528/c1a8f1fa-846f-11e5-9cca-cf2473b856ac.png)
But why?
Gesamt (netto) is ok.
(Magento Version 1.9.2.1)

**Comment by sprankhub** [comment]
Afaik, this is an issue in an old version. Please update to the latest version 1.3.0 or to the current development branch.
