### ISSUE TITLE
Regarding pdf

### ISSUE THREAD

**Issue by aneeshjajodia** [firegento/firegento-pdf#288]
Hello

Please help me on how to generate and download the pdf?

**Comment by SilentAce** [comment]
If you are referring to the settings then in System->Configuration under the Sales->PDF print-outs the option PDF Engine sets the invoice that is generated. 
If you don't know how to process an order to generate the pdf here is a complete step by step https://www.youtube.com/watch?v=w27quOkD9Ig. The invoices are under Sales->Invoces selecting from the Actions dropdown - PDF Invoices - and Submit.

**Comment by aneeshjajodia** [comment]
Though I selected the configurations and stuff, the PDF invoices still come this way, that is the stock magento style.

I would be really glad if you could help me through. 

<img width="1440" alt="screenshot 2015-11-10 16 35 46" src="https://cloud.githubusercontent.com/assets/1062704/11060894/234a94e8-87c9-11e5-9e75-702d15ee9c97.png">

**Comment by sprankhub** [comment]
You have to select the FireGento engine in the configuration:

![image](https://cloud.githubusercontent.com/assets/930199/11060929/c0756124-87a3-11e5-897a-cc148dee6473.png)

**Comment by aneeshjajodia** [comment]
<img width="549" alt="screenshot 2015-11-10 16 39 42" src="https://cloud.githubusercontent.com/assets/1062704/11060968/ab24f002-87c9-11e5-90fa-936dfd332224.png">

These are the only two options available at my end.

**Comment by sprankhub** [comment]
Then select "Standard Germany". And you should consider an upgrade of our extension.

**Comment by aneeshjajodia** [comment]
Hello,

Please can you let me know how to upgrade it?

Also, in the Sender Address Bar: I wanted to have my company name in two lines, can you help me through it?

Aneesh Jajodia

On 10 November 2015 at 16:41:07, Simon Sprankel (notifications@github.com) wrote:

Then select "Standard Germany". And you should consider an upgrade of our extension.

**Comment by sprankhub** [comment]
Read any tutorial how to update an extension. In the simplest case, download the files and upload them to your store.

Two lines is not supported by default. You can write your own engine if you like to (see Wiki).

**Comment by aneeshjajodia** [comment]
Thanks a lot mate. 😃

Is it possible to add a picture in this?

I can create a picture then with the logo and the address.

**Comment by sprankhub** [comment]
No, it is not.

**Comment by aneeshjajodia** [comment]
Would be glad if you guys come up with the image thing. 😃


Aneesh Jajodia

On 10 November 2015 at 16:45:54, Simon Sprankel (notifications@github.com) wrote:

No, it is not.
