### ISSUE TITLE
Show Human Readable Error When Interlaced Image Is Uploaded

### ISSUE THREAD

**Issue by snap15** [firegento/firegento-pdf#289]
Hi, we upgraded the mangento DE version (1.9.1 v4) to "normal" Magento 1.9.2.2 cause of the security patch 6788. We already upload the newest version of firegento pdf. Unfortunately we can't safe or print invoices from backend still get error message: Exception printing is disabled by default for security reasons. We already checked under PDF Engine "Magento Deutschland".
Any idea? Any fixes or bugs depending on 1.9.2.2?

**Comment by Schrank** [comment]
Hi, please read http://magento.stackexchange.com/a/429/217 and report back with a "real" error message :-)

**Comment by snap15** [comment]
??? 
Error message after click on print invoice:
Only non-interlaced images are currently supported.

Trace:
#0 /var/customers/webs/.../.../lib/Zend/Pdf/Resource/ImageFactory.php(54): Zend_Pdf_Resource_Image_Png->__construct('/var/customers/...')
#1 /var/customers/webs/.../.../lib/Zend/Pdf/Image.php(124): Zend_Pdf_Resource_ImageFactory::factory('/var/customers/...')
#2 /var/customers/webs/.../.../app/code/community/FireGento/Pdf/Model/Engine/Abstract.php(301): Zend_Pdf_Image::imageWithPath('/var/customers/...')
#3 /var/customers/webs/.../.../app/code/community/FireGento/Pdf/Model/Engine/Abstract.php(254): FireGento_Pdf_Model_Engine_Abstract->_insertLogoPositioned(Object(Zend_Pdf_Page), Object(Mage_Core_Model_Store))
#4 /var/customers/webs/.../.../app/code/community/FireGento/Pdf/Model/Engine/Abstract.php(404): FireGento_Pdf_Model_Engine_Abstract->insertLogo(Object(Zend_Pdf_Page), Object(Mage_Core_Model_Store))
#5 /var/customers/webs/.../.../app/code/community/FireGento/Pdf/Model/Engine/Invoice/Default.php(73): FireGento_Pdf_Model_Engine_Abstract->insertAddressesAndHeader(Object(Zend_Pdf_Page), Object(Mage_Sales_Model_Order_Invoice), Object(Mage_Sales_Model_Order))
#6 /var/customers/webs/.../.../app/code/community/FireGento/Pdf/Model/Invoice.php(78): FireGento_Pdf_Model_Engine_Invoice_Default->getPdf(Array)
#7 /var/customers/webs/.../.../app/code/community/FireGento/Pdf/controllers/Adminhtml/Sales/Order/InvoiceController.php(46): FireGento_Pdf_Model_Invoice->getPdf(Array)
#8 /var/customers/webs/.../.../app/code/core/Mage/Core/Controller/Varien/Action.php(418): FireGento_Pdf_Adminhtml_Sales_Order_InvoiceController->printAction()
#9 /var/customers/webs/.../.../app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('print')
#10 /var/customers/webs/.../.../app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#11 /var/customers/webs/.../.../app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#12 /var/customers/webs/.../.../app/Mage.php(684): Mage_Core_Model_App->run(Array)
#13 /var/customers/webs/.../.../index.php(83): Mage::run('', 'store')
#14 {main}

**Comment by snap15** [comment]
Sorry, already found the solution... uploaded wrong image (interlaced) to "Konfiguration --> Verkäufe --> Rechnungs- und Lieferscheingestaltung "

**Comment by Schrank** [comment]
Super :)

**Comment by Schrank** [comment]
Simon, we should catch this error and show in the frontend!

**Comment by sprankhub** [comment]
Duplicate of https://github.com/firegento/firegento-pdf/issues/205
