### ISSUE TITLE
E-Mail and Invoice Translations doesn't functioning

### ISSUE THREAD

**Issue by lazolive** [firegento/firegento-pdf#290]
E-MAIL
-------    START of IMAGE    ---------
![translation_error](https://cloud.githubusercontent.com/assets/13330167/11117835/53e3c780-893d-11e5-9a4b-12569be8378f.jpg)
-------    END of IMAGE    ---------

I Have a BIG/FATAL: "Translation" Problem. As you can see in the image below, is a part of the E-Mail in English and a part in German.

-----------------------------------------------------------------------------------------------------------------------------
INVOICE
-------    START of IMAGE    ---------
![invoice2015-11-12_12-10-05_001](https://cloud.githubusercontent.com/assets/13330167/11117765/d07df7da-893c-11e5-92bc-a31638dd1ae9.jpg)
-------    END of IMAGE    ---------

-----------------------------------------------------------------------------------------------------------------------------
All of the English Words, I have translated in the following files:
-> magento/app/locale/de_DE/FireGento_GermanSetup.csv
-> magento/app/locale/de_DE/FireGento_Pdf.csv
-> magento/app/locale/de_DE/IntegerNet_MagentoLocalized.csv
-> magento/app/locale/de_DE/Mage_Adminhtml.csv
-> magento/app/locale/de_DE/Mage_Payment.csv
-> magento/app/locale/de_DE/Mage_Sales.csv
-> magento/app/locale/de_DE/Mage_Shipping.csv
-> magento/app/locale/de_DE/translate.csv
-> magento/app/design/adminhtml/default/default/locale/de_DE/translate.csv

I need really fast and a clear solution to translate these thing in to German Language...
Am I the only one, who is using Magento CE - DE Version 1.9 of netresearch with this fatal problem?

Thanks in advance for your assistance....!

**Comment by sprankhub** [comment]
I normally do not use the DE version, but it should normally work out of the box I think. This sounds like a general translation configuration issue which is not directly linked to the PDF extension. Make sure that:

1. The [german language pack](https://github.com/riconeitzel/German_LocalePack_de_DE) is properly installed (normally included in the DE version I guess).
2. The german locale is set in the respective store view under System - General - Locale Options - Locale.
