### ISSUE TITLE
Footer not displaying

### ISSUE THREAD

**Issue by razorblade1990** [firegento/firegento-pdf#291]
Hi, I just installed this extension and it's working great after some configuration. But it seems it doesn't want to show the footer in the PDF at all. Everything is setup correctly and my store details have been input into magento. It's just that the footer doesn't show on the PDF files.

Is this a bug or is there something wrong elsewhere? I'm running the latest magento (1.9.2.2). Thanks in advance!

**Comment by Schrank** [comment]
Did you turn on the footer? I don't know of any bug yet.
![bildschirmfoto 2015-11-15 um 16 52 33](https://cloud.githubusercontent.com/assets/379680/11169465/56762532-8bb9-11e5-9320-fd95a2b1cb98.png)

**Comment by razorblade1990** [comment]
Yes I did and cleared cache (for in the remote chance that that could've been it) but it's just not showing any footer at all... Is it maybe that somewhere else in Magento I should configure some things?

**Comment by razorblade1990** [comment]
And I'm using the custom (Deutschland) PDF, maybe usefull information as well?

**Comment by Schrank** [comment]
No clue - sorry. What I can offer you is to check it on your instance. If it is a bug I'll fix it, if it is not I'll send you an invoice

**Comment by razorblade1990** [comment]
That's okay. To what do you need permission?

**Comment by Schrank** [comment]
What about changing the medium? Give me a call, send me an email: http://fabian-blechschmidt.de/

**Comment by razorblade1990** [comment]
Changing the medium? Like changing the template you mean back to the default magento template? Tried that already and didn't work either :(
