### ISSUE TITLE
Article Desc overlaping Price

### ISSUE THREAD

**Issue by unifiedarts** [firegento/firegento-pdf#295]
is there a way to make text wrapping active when the text reach the border of the column? for now the article description is overlapping the price.

socond thing, is it right that the special and regular prices are not showen both in the pdf invoice? i think there is just one of them two.

here an screenshot of what i mean with overlapping:
![overlapping](https://cloud.githubusercontent.com/assets/7428697/11441574/b8d1b4a0-950d-11e5-8bd3-4ffdb991e931.jpg)
thx for advice!

**Comment by Schrank** [comment]
Are you using current develop branch?

**Comment by unifiedarts** [comment]
nope, are the any recent updates? is this issue also fixed?

**Comment by Schrank** [comment]
Not sure, but master is 100 commit behind.

**Comment by unifiedarts** [comment]
k, will check the dev branch, thx

**Comment by Schrank** [comment]
If this is still an issue, please tell us.
