### ISSUE TITLE
Improve usage of sales_pdf/invoice/show_customer_number option

### ISSUE THREAD

**Issue by pquerner** [firegento/firegento-pdf#299]
Hi,

currently you can only set this field ```sales_pdf/invoice/show_customer_number``` to either yes, or no. (Which makes sense in the current variable name)
We should be able to select what field to use as the customer number as an extra field perhaps.
Because in our case we like to use the ```increment_id``` of the customer instead.

I had to change it in a observer. So it is possible, but should be easier to configurable from the backend directly.

**Comment by Schrank** [comment]
We would love to get a PR from you on this!

**Comment by pquerner** [comment]
Is merged. https://github.com/firegento/firegento-pdf/pull/300
