### ISSUE TITLE
Is there is an example to use?

### ISSUE THREAD

**Issue by mymicroblog** [firegento/firegento-pdf#301]
Is there is an example to use?

**Comment by Schrank** [comment]
Do you mean a pdf you can look at? No it is an open ticket #292
Or how to install it? Is in README: https://github.com/firegento/firegento-pdf#installation-instructions

**Comment by mymicroblog** [comment]
Sorry,I mean if there is an example for php to use and it can generate a pdf invoice.Thank you

**Comment by sprankhub** [comment]
Do you even use Magento? If not, this is nothing you want to use.

**Comment by mymicroblog** [comment]
yes ,I consider to user it . My target is generate a pdf invoice.Is there any examples or document ?

**Comment by Schrank** [comment]
Unfortunately not: https://github.com/firegento/firegento-pdf/issues/292
