### ISSUE TITLE
Firegento in magento email

### ISSUE THREAD

**Issue by heikostueber** [firegento/firegento-pdf#303]
Hi,
is it possible to use the good looking firegento PDF documents instead of the magento ones in emails and customer prints?

The situation: 
The customer get the invoice by email or the customer use the print function in his account.. The email looks very different and so there is no corporate identity anymore.

br
Heiko

**Comment by sprankhub** [comment]
This is already the case. If the PDF is sent as an attachment via email, the FireGento layout is used (if configured). Same if the customer prints it in the frontend.

Make sure that you use the latest version and that you configured the "Standard FireGento" engine in the system configuration.

**Comment by Schrank** [comment]
If you want to attach the invoice, you can e.g. use https://github.com/fooman/emailattachments

**Comment by heikostueber** [comment]
Hi,
thx for the fast answers.

I configured the pdf prints. Is there another point to configure?
How can I see the version of firegento?

@Schrank Thanks for the link.

br
Heiko

**Comment by heikostueber** [comment]
Hi,

I forgot some information,
I'm using the magento german community edition 1.9.1.0

**Comment by sprankhub** [comment]
System - Configuration - PDF Print-Outs. There you have to configure the correct engine.

You see the version under `app/code/community/FireGento/Pdf/etc/config.xml`.

**Comment by heikostueber** [comment]
I have version 1.3 

I configured the PDF Print-Outs, but I get only the firegento PDF if I'm printing from admin. No firegento is used in customer print or email.

**Comment by sprankhub** [comment]
You could try the [current development branch](https://github.com/firegento/firegento-pdf/archive/development.zip). Unfortunately, we did not release a new version for too long.

How do you attach the PDFs to the emails?

**Comment by heikostueber** [comment]
I took a look at fooman, but I didn't installed it at this time.

**Comment by sprankhub** [comment]
But you say that the PDF in the email has the wrong design...? So how do you attach the PDFs to the mails?

**Comment by Schrank** [comment]
Make sure it is not overwritten on store view level

Von unterwegs gesendet

**Comment by heikostueber** [comment]
@Schrank You're right, I solved the issue . THX

@sprankhub  Thank you too.

Great extension !
