### ISSUE TITLE
Creditmemo & Payment Type

### ISSUE THREAD

**Issue by unifiedarts** [firegento/firegento-pdf#304]
we noticed that there is no info about the payment type on the creditmemo. also checked the admin settings for that. just for invoicing is an field related to payment, not on the creditmemo.

did we overlooked any settings or is there simply no choise of that. if so, then it would be nice to have an hint where we can add that thru the code.

thanks in advance
florin

**Comment by Schrank** [comment]
Hi, what do you mean? Write on the creditmemo what payment type the customer used or what you use to send the money back?

**Comment by unifiedarts** [comment]
what payment type the customer used

**Comment by unifiedarts** [comment]
FireGento_Pdf_Model_Engine_Abstract - row 647. i suggest this is the right place for extending the functionality?

**Comment by sprankhub** [comment]
The [FAQs](https://github.com/firegento/firegento-pdf/wiki/FAQs) show how you can customise the PDF (namely observers vs custom engines).

I admit that the payment method also makes sense on the creditmemo, so a config option would be nice anyway.

**Comment by Schrank** [comment]
A PR is welcome :-)
