### ISSUE TITLE
Order number on invoice pdf, no config option

### ISSUE THREAD

**Issue by codedge** [firegento/firegento-pdf#306]
Hey,
did I miss the config option or is there no way to display the order number on an invoice?
If there is no option, I would prepare a pull request, ok?

Cheers, Holger

**Comment by Schrank** [comment]
There is, at least in the version I use :-) Try the develop branch!

![bildschirmfoto 2016-02-14 um 16 21 42](https://cloud.githubusercontent.com/assets/379680/13034493/27f109fa-d337-11e5-8969-56a32633349b.png)

**Comment by codedge** [comment]
Ahh.. I meant the order date - sry :-( Is there an option for the order date?

**Comment by Schrank** [comment]
Don't think so. And I think it doesn't make sense to put it in the header to avoid confusion with the invoice date. So an observer would be a good idea to put it into notes? And an edit to the wiki would be great! I don't want it in core. @sprankhub ?

**Comment by sprankhub** [comment]
I also do not think that it really makes sense in the core. An observer for the data in the top right block would be nice though. See #307.
