### ISSUE TITLE
Store setting after locale emulation is causing problems when using a different admin URL

### ISSUE THREAD

**Issue by digitalpianism** [firegento/firegento-pdf#309]
Ok let's say I've got the following:
- Frontend: www.store.com
- Backend: admin.www.store.com

When an engine of the module is called via the backend, the following code is triggered (example for shipment):

`if ($shipment->getStoreId()) {
                Mage::app()->getLocale()->emulate($shipment->getStoreId());
                Mage::app()->setCurrentStore($shipment->getStoreId());
            }`

Problem is, at the end of the code, the current store is not reverted.

Thus, it is causing the backend to be redirected from admin.www.store.com to the URL corresponding to the shipment store.

I'm about to create a pull request for this specific problem right now

**Comment by Schrank** [comment]
Please do :-) Looking forward to the PR!

**Comment by digitalpianism** [comment]
https://github.com/firegento/firegento-pdf/pull/310
