### ISSUE TITLE
Paypal Plus

### ISSUE THREAD

**Issue by KlausGw** [firegento/firegento-pdf#311]
Hi!
I have integrated Paypal Plus.
So far so good.
But the PDF invoice is not correct, if purchase invoice was chosen as the payment method.
It lacks there the bank data of Paypal.
Is there a solution?

**Comment by sasoriza** [comment]
I assume you are using the i-ways PayPal Plus extension. You should report this bug directly to ppp-support@i-ways.de. The template provided by i-ways is missing this information, nothing Firegento can do about that.

**Comment by KlausGw** [comment]
Sure it's a bug in i-ways PayPal Plus extension? The payment information is not displayed in the firegento pdf. I tested with the magento standard pdf engine and there are all related informations about the payment.

**Comment by Schrank** [comment]
Hey, thanks for your report. Did you check whether the extension is rewriting the invoice_pdf? Is the extension anywhere available, so I can have a look?

**Comment by KlausGw** [comment]
It is a test shop in Sandbox mode. Not public.
Live shop without PayPal invoice purchase, but with Paypal Plus: http://www.weinwelt-probst.de/

**Comment by Schrank** [comment]
No, I'm talking about source code :-) I can't find it on github.

**Comment by sprankhub** [comment]
@Schrank I have it and will check it. I think it is the same issue as #94. We never show the detailed information, we only show the title. I will probably implement and publish extensions, which show the detailed Billpay / PayPal Plus information in the comments section.

**Comment by Schrank** [comment]
Yea, that was my idea too. But why not showing everything?

**Comment by sprankhub** [comment]
Because we simply do not have enough space in the top right corner for full payment information with an explanation sentence, bank data etc.

**Comment by Schrank** [comment]
Of course. Had the original invoice in mind :-(

**Comment by sprankhub** [comment]
@Schrank do you have the rights to create new FireGento repos? If so, please create:

- firegento-pdf-billpay
- firegento-pdf-paypalplus

And give the same people access as the ones from firegento-pdf.

If not, maybe @therouv can quickly help us out.

**Comment by KlausGw** [comment]
Extension: https://www.paypal-viewpoints.com/paypal-plus-integration

**Comment by therouv** [comment]
@sprankhub @Schrank repositories are created

**Comment by sprankhub** [comment]
@therouv thanks!

@KlausGw I implemented an extension which should add the detailed PayPalPlus payment information on our invoices: https://github.com/firegento/firegento-pdf-paypalplus. Since I do not have a shop, where I can easily test it, could you please test it and provide some feedback? Thanks!

**Comment by KlausGw** [comment]
Trying to get property of non-object  in /home/weinwelt/testshop/app/code/community/FireGento/PdfPayPalPlus/Model/Observer.php on line 45

**Comment by sprankhub** [comment]
Oh boy, sorry! Please update and test again...

**Comment by KlausGw** [comment]
PHP Fatal error:  Call to a member function getCode() on a non-object in /home/weinwelt/testshop/app/code/community/FireGento/PdfPayPalPlus/Model/Observer.php on line 45

**Comment by sprankhub** [comment]
And again please :)

**Comment by KlausGw** [comment]
Great!
Only missing line breaks.

PayPal Plus Bitte überweisen Sie den Rechnungsbetrag auf das angegebene Konto innerhalb der
Zahlungsfrist. Kontoinhaber: PayPal Europe Bank: Deutsche Bank IBAN: DE21120700888000008539 BIC: DEUTDEDBPAL Verwendungszweck: 40V34919MW712335Y Fälligkeitsdatum: 03.04.2016

**Comment by sprankhub** [comment]
Nice. Please update and try again. Do you have line breaks now?

**Comment by KlausGw** [comment]
PayPal Plus

Bitte überweisen Sie den Rechnungsbetrag auf das angegebene Konto innerhalb der Zahlungsfrist.
Kontoinhaber: PayPal Europe
Bank: Deutsche Bank
IBAN: DE21120700888000008539
BIC: DEUTDEDBPAL
Verwendungszweck: 40V34919MW712335Y
Fälligkeitsdatum: 03.04.2016

Der Rechnungsmonat entspricht dem Leistungsmonat. Dieser Hinweis entspricht §31 Abs. IV USTDV.

Vielen Dank für Ihre Bestellung!

**Comment by KlausGw** [comment]
Thank you very much!

Now I need to test how it is when there are multiple pages.

**Comment by sprankhub** [comment]
Awesome, glad that it works. If you have any more issue with the PayPalPlus integration, please open an issue in the corresponding repository.
