### ISSUE TITLE
Change invoice note based on customer group

### ISSUE THREAD

**Issue by 4ntz** [firegento/firegento-pdf#312]
I would like to fill out some notes in the backend depending on the user group. So in the end I want different text appearing on the invoices for different user groups.

How could I manage to do that?

**Comment by Schrank** [comment]
Head over to the wiki, implement your own observer, check the customer group and add the note:
https://github.com/firegento/firegento-pdf/wiki/FAQs#how-can-i-add-notes-to-the-pdfs-programmatically

**Comment by sprankhub** [comment]
You would have to code that yourself. But it is quite straightforward and can be done via event observers - see the explanation in our [wiki](https://github.com/firegento/firegento-pdf/wiki/FAQs#how-can-i-add-notes-to-the-pdfs-programmatically).
