### ISSUE TITLE
Duplicate Tax

### ISSUE THREAD

**Issue by robinbirr** [firegento/firegento-pdf#313]
Hey guys,
in my PDF's i have duplicate tax info.
e.g.:
![tax](https://cloud.githubusercontent.com/assets/6839515/14177598/50f43662-f757-11e5-9e7c-740f3b163edb.jpg)

How can i delete the second tax rate info without the 19%?

**Comment by sprankhub** [comment]
Magento separates the taxes:

- Separate entry for the shipping tax (none in your case).
- Separate entries for each tax rate (7% / 19%) ("DE - USt. (19,00% in your case)").
- Entry summarising all taxes ("Steuer" in your case).

I do not see any possibility to change this easily and reliably.
