### ISSUE TITLE
Attach PDF with e-mail

### ISSUE THREAD

**Issue by ecowebdesign** [firegento/firegento-pdf#315]
I am not getting attached PDF together with the order e-mail. 
People where suggesting Fooman extension , but it does not work together.
Anyone got it working ?

**Comment by Schrank** [comment]
Yes, works like a charm for me: https://github.com/fooman/emailattachments

**Comment by ecowebdesign** [comment]
Thanks, but I am out of luck , because when enabling this , e-mails are going nowhere, no error reports.

**Comment by sasoriza** [comment]
That's odd, I can confirm Fooman Email Attachments works flawlessly along with FiregentoPDF

**Comment by sprankhub** [comment]
Same for me. Works without any issues. If you do not get any errors, have a look at [this](https://magento.stackexchange.com/questions/428/fundamentals-for-debugging-a-magento-store).

**Comment by Schrank** [comment]
@ecowebdesign The only thing we can offer is personal, paid support!
