### ISSUE TITLE
including own attributes delivery_time and weight 

### ISSUE THREAD

**Issue by MaSnWh** [firegento/firegento-pdf#317]
Hello:)

I want to include "delivery_time" for every product and weight as subtotal - has anybody an idea how?

Thanks you so much
Maria
_________________________________________________________
Hallo:)

Ich möchte die Attribute "delivery_time" bei jedem Produkt dazuschreiben lassen und das Gewicht aller Produkte als Summe - hat jemand eine Idee wie ich das bewerkstelligen könnte?

Danke euch schon mal
Maria

**Comment by Schrank** [comment]
I think the easiest would be to implement your own renderer. For this you need to overwrite `global/pdf/default`.

Example can be found here:

    app/code/core/Mage/Sales/etc/config.xml:1429

    <global>
        <pdf>
            <invoice>
                <default>sales/order_pdf_items_invoice_default</default>
                <grouped>sales/order_pdf_items_invoice_grouped</grouped>
            </invoice>
            <shipment>
                <default>sales/order_pdf_items_shipment_default</default>
            </shipment>
            <creditmemo>
                <default>sales/order_pdf_items_creditmemo_default</default>
                <grouped>sales/order_pdf_items_creditmemo_grouped</grouped>
            </creditmemo>

Then you can do in in the draw method whatever you want.You can either inherit from `FireGento_Pdf_Model_Items_Default` or `Mage_Sales_Model_Order_Pdf_Items_*(Invoice)_Default`.

About the weight, I recommend to implement an observer and just add a sentence to the note section, as described here: https://github.com/firegento/firegento-pdf/wiki/FAQs#how-can-i-add-notes-to-the-pdfs


This ticket stays open until someone added the renderer part to FAQ.

**Comment by Schrank** [comment]
Sorry, I was wrong, the renderers are defined here:

    \FireGento_Pdf_Model_Engine_Creditmemo/Invoice/Shipment_Default::_initRenderer


We should fix this, why is this hardcoded!?

TODO: Use config for renderers.

**Comment by mam08ixo** [comment]
I do not agree with this being an issue. Once you have your own PDF engine in place, you gain full control over the applied item renderers. The given requirements can be fully met with the current state of the `FireGento_Pdf` extension.

See one possible approach in [my PdfSkeleton module](https://github.com/mam08ixo/pdf-skeleton/tree/pdf-317). It surely needs a solid finish but points into a valid direction.

**Comment by Schrank** [comment]
But why not make it configureable? Then you don't need to implement your own engine but just can switch the renderer?

**Comment by sprankhub** [comment]
I think this is a rather rare case. Making it configurable on a code level via XML is fine for me. But I vote against another admin configuration option.

**Comment by Schrank** [comment]
I totally agree here. No option in backend, only XML

**Comment by mam08ixo** [comment]
In my personal opinion it is simply unnecessary (and to some degree confusing) to bring in yet another way of achieving the same thing. The effort of writing a custom engine is close to insignificant. I would rather stick to that single, well-documented entry point for altering the PDF layout.

I do not see a use case here either. Who needs to tweak the item list but stays with the in-built renderer for the rest of the document?

Just my two cents. If you want to implement it, go for it.

**Comment by sprankhub** [comment]
I get your point @mam08ixo and second it. Let us stick to a single entry point for customisation. @Schrank fine for you or do you want to implement it nevertheless?

**Comment by Schrank** [comment]
Open source should be democratic if possible :)
