### ISSUE TITLE
Question: How to add more whitespace

### ISSUE THREAD

**Issue by epiblue** [firegento/firegento-pdf#319]
Hello Guys,

I appologize for the stupid question, but I can't find the value or way to add more space between the customer details and the bought items table.

Can you point me in the right direction please?

Thank you,

**Comment by Schrank** [comment]
Throughout the whole PDF the position of more or less everything is defined by `$this->y`, so just increase y and you get more space.

**Comment by epiblue** [comment]
I'm trying to affect this value, but I cant find the correct one to make more space between the Client deteils and products tables. 

Some clients have a lot of values and text is overlapping.

Can you point me to the correct file? Please...

**Comment by Schrank** [comment]
Have a look here: https://github.com/firegento/firegento-pdf/pull/279

**Comment by epiblue** [comment]
Thanks, this helped me to move the table, but the word "Invoice" did not move.

I've modified this code:
```
    protected function insertAddressesAndHeader(
        Zend_Pdf_Page $page,
        Mage_Sales_Model_Abstract $source,
        Mage_Sales_Model_Order $order
    ) {
        // Add logo
        $this->insertLogo($page, $source->getStore());

        // Add billing address
        $this->y = 692 - $this->_marginTop;
        $this->_insertCustomerAddress($page, $order);

        // Add sender address
        $this->y = 705 - $this->_marginTop;
        $this->_insertSenderAddessBar($page);

        // Add head
        $this->y = 592 - $this->_marginTop;
        $this->insertHeader($page, $order, $source);

        /* Add table head */
        // make sure that item table does not overlap heading
        if ($this->y > 475 - $this->_marginTop) { <!-- This was originaly 575
            $this->y = 475 - $this->_marginTop;
        }
    }

```

**Comment by Schrank** [comment]
// Add head
        $this->y = 592 - $this->_marginTop;
        $this->insertHeader($page, $order, $source);

This code is inserting the header (invoice, creditmemo, shipment), so changing the value of $this->y is changing the position of the headline.

Beside this, I don't know how you change everything, but you can "implement" your own engine (https://github.com/firegento/firegento-pdf/wiki/FAQs#how-can-i-put-some-fancy-stuff-wherever-i-want-to-without-writing-my-own-engine) so you might want to do this instead of rewriting or worst case just hacking the files.

**Comment by epiblue** [comment]
Thanks for the help. I've managed to move it, it's not perfect but it suits our needs, 

I will definatelly investigate the engine material that you've mensioned.

Thanks a lot for your help !!

**Comment by Schrank** [comment]
If you need help, feel free to mail @sprankhub or me, we both are freelancers :-)
