### ISSUE TITLE
Nothing change

### ISSUE THREAD

**Issue by 4lternative** [firegento/firegento-pdf#320]
Hi,

I've just installed your extension on a magento 1.9.1 but nothing seems to impact the pdf. 

Is it maybe because I have something in app/code/local/Mage/Sales/Model/order/Pdf/ ? 

Thank you for your help

**Comment by Schrank** [comment]
Not sure. But I assume no, because we rewrite the Pdf models. Did you clear the cache?

**Comment by 4lternative** [comment]
Yes I did clear the cache.

I've tried renaming the app/code/local/Mage/Sales/Model/order/Pdf/ folder in OLD just to see if it change something, and it did. But it doesn't seems to get info from the extension. By that I mean, I guess it's going to look for the app/core/... default template. 

The only thing that seems to work it's the Filename Export Pattern

Thank you for you quick anwser

**Comment by Schrank** [comment]
Sorry, if you hacked your system, there is not much we can do to analyze the problem from here. I can offer you to have a look as a freelancer on the problem. If you are interested just send me an email firegentoPdf@fabian-blechschmidt.de or @sprankhub mail@simonsprankel.de

Sorry that the module doesn't work out of the box.

**Comment by sprankhub** [comment]
Did you change the engine in the system configuration?

**Comment by 4lternative** [comment]
By default, it's on Standard Magento, and in the dropdown list I only have two choice : **Standard Magento** and **Standard Germany**

I've let it on "Standard Magento"

**Comment by sprankhub** [comment]
Change it to Standard Germany and you will see the new layout.

**Comment by 4lternative** [comment]
Great, it work thank you for the help ! And great work guys

Last question, for the translation, I need to it throught the extension folder or through the global translation file of magento ? If it's through the module, what files I need to look at ?

**Comment by sprankhub** [comment]
You can do it in "any" translation file, which is used in your Magento translation (depends on the string).
