### ISSUE TITLE
Remove line from bottom details

### ISSUE THREAD

**Issue by 4lternative** [firegento/firegento-pdf#321]
Hello,

In which file can I handle what is displaying after the table :

![capt](https://cloud.githubusercontent.com/assets/19288260/15156851/362fdf0a-16e9-11e6-82e2-b9d9acebb7d2.PNG)

For exemple, I'd like to remove the line TVA (20%).

Thank you

**Comment by sprankhub** [comment]
You cannot configure that. This is all Magento standard.

You should be able to translate the labels via the translation files though.

**Comment by sprankhub** [comment]
Well, you can configure it a little bit in the system configuration under the tax tab. But possibilities are quite limited.
