### ISSUE TITLE
No total price for Bundle Products

### ISSUE THREAD

**Issue by anjenehm** [firegento/firegento-pdf#322]
Hey we just published some bundle products. 
As we want to creat the bill for us an the customer,
the total price is 0€. So where is the issue is it a firegento problem or magento?

(see it on the screenshot)

![image](https://cloud.githubusercontent.com/assets/7089704/15536222/b3d3493c-2270-11e6-8741-2b668610eade.png)

Thanks for quick help!

Best regards,

Basti

**Comment by Schrank** [comment]
Never heard of that problem. I assume, because a lot of people use the module, this is a local problem. Unfortunately I don't have time currently to look into this.

**Comment by anjenehm** [comment]
So any idea for a quick fix with a extension?

Thanks for your quick response!

**Comment by sprankhub** [comment]
This is an issue of an old version of the extension. Please use the current development branch and your issue should be fixed.
