### ISSUE TITLE
Packing slip not working!

### ISSUE THREAD

**Issue by kims8-bit** [firegento/firegento-pdf#323]
I have been modifying the layout for Invoice and Creditmemo, but when I started to change the packing slip PDF, I noticed, that the engine is never called??!!
I already enabled my custom engine in settings, and tried changing it to German Setup as well, but nothing changes, I always get the standard Magento Packing Slip!

The Invoice and Creditmemo works as expected.

Hope someone can guide me on the way on this

**Comment by kims8-bit** [comment]
I have been investigating this issue on a fresh installed Magento 1.9.2.4 and found that I was unable to print the packing slip directly from the order page as I can on my live shop!
I found that this feature is added by Fooman Email Attachements, so I tried creating a Shipment and print out the Packing Slip from there which works as I had expected :)

So to sum it up, Fooman Email Attachements and FireGento PDF extension must have some sort of conflict, but as I'm pretty novice in Magento programming, I'm unable to solve it by myself.

Hopefully someone is able to solve the issue :)

**Comment by Schrank** [comment]
Can you please add a screenshot or a couple? I don't understand where to click to reproduce the issue :)

**Comment by sprankhub** [comment]
@kims8-bit please add screenshots and/or a more specific description. I use Fooman Email Attachments together with FireGento PDF in multiple shops and did not encounter any issues. What do I have to do to reproduce your issue?

**Comment by kims8-bit** [comment]
After testing a bit last night, I found that the shipment pdf (Packing Slip) is generated by Fooman Email Attachements extension!
The other PDF's are generated using the FireGento PDF engine!
I have attached some pictures. the packing slip is wrong (Fooman extension created), the invoice and creditmemo are correct.

**Configuration:**
![pdf-printouts](https://cloud.githubusercontent.com/assets/19592646/15608851/b335f4c2-241c-11e6-92fd-bec965cec554.png)

**Order View (this is where I print out the packing slip):**
![order view](https://cloud.githubusercontent.com/assets/19592646/15608858/bc8c17ea-241c-11e6-9a21-2244c7662610.png)

**Packing Slip (wrong design):**
![packing slip](https://cloud.githubusercontent.com/assets/19592646/15608867/c6af70fa-241c-11e6-9e81-5b916bfc6d92.png)

**Invoice (correct design)**
![invoice 1](https://cloud.githubusercontent.com/assets/19592646/15608873/d04a1f2a-241c-11e6-827f-46c5318bf623.png)

**Credit memo (Correct design)**
![creditmemo](https://cloud.githubusercontent.com/assets/19592646/15608876/d7074306-241c-11e6-8e1f-d213eaad408c.png)

**Comment by sprankhub** [comment]
Thanks for the clarification. This is NOT the packing slip. This is a simple print-out of the order. This is not (yet) supported and may be fixed with https://github.com/firegento/firegento-pdf/pull/297. You can print the packing slip under the Shipments tab of the order. The shipment print-out is the packing slip.
