### ISSUE TITLE
Store Address

### ISSUE THREAD

**Issue by davidbarman** [firegento/firegento-pdf#324]
Is there a way to add the store's street address to the invoice?  Perhaps to the right of the logo at the top?  Please advise.  Thank you.

**Comment by sprankhub** [comment]
Do you use [MageSetup](https://github.com/firegento/firegento-magesetup)?

- If you do and you enable the footer in the PDF configuration, the store address from the imprint will be shown in the footer.
- If you do not, you can still enable the footer in the PDF configuration and add the store address via [`config.xml`](https://github.com/firegento/firegento-pdf/wiki/FAQs#how-can-i-add-a-footer-without-using-germansetupmagesetup).
- If you do not want it to be shown in the footer, you can still use one of the other methods (observer / own engine) described in the [FAQs](https://github.com/firegento/firegento-pdf/wiki/FAQs).
