### ISSUE TITLE
Tableheader of Creditmemo/Default.php is wrong

### ISSUE THREAD

**Issue by nige-one** [firegento/firegento-pdf#326]
Not sure why Creditmemo uses another Tableheader function `_drawHeader` then Invoice `insertTableHeader`. Anyway, it does not work correctly. After copying the content of `insertTableHeader` into `_drawHeader` everything works fine. I guess it's an legacy issue.

**Comment by sprankhub** [comment]
The reason is that the columns of the invoice are configurable, whereas the columns of the creditmemo are not.

For me, this works perfectly fine. What exactly does not work? Do you have any error?

**Comment by nige-one** [comment]
Try to change the column order. Although the creditmemo tableheader column order is currently fixed, the item rendering respects the configured column order so it does not match up.

**Comment by zuiko** [comment]
The solution is to take the same columns configuration for creditmemo than invoice. In my mind, there is no reason why they could be different...

**Comment by Schrank** [comment]
I think step a) is to use the same, step b) to have a second/third configuration for creditmemo and shipping

**Comment by zuiko** [comment]
I agree,
who can do most can do least... Most often.
