### ISSUE TITLE
Invoice Note - Modify font's color

### ISSUE THREAD

**Issue by 4lternative** [firegento/firegento-pdf#329]
Hello guys,

This is not a real issue, so I'm sorry for opening this as one.

I would like to knowin which file the Note (printed on every invoice) is define so I can change the color of the font ? 

Thanks

**Comment by Schrank** [comment]
May I recommend to search the code before opening issues? :-)

    FireGento_Pdf_Model_Engine_Abstract::_insertNote

**Comment by sprankhub** [comment]
Additionally, many notes are added in the observer `FireGento_Pdf_Model_Observer`.

**Comment by Schrank** [comment]
Then sorry for ranting :o)

**Comment by 4lternative** [comment]
Thank for your answers. I did look at the code, and did it again with your clues, but can't find the right place. I found where the shipment, payment et other notes are, but not the one i'm looking for. I'm also not a php master, so maybe I'm missing something. I'm giving up, thanks anyway

**Comment by Schrank** [comment]
That is of course not intended :) No one is left behind (if possible).

Here the note is written:
https://github.com/firegento/firegento-pdf/blob/development/src/app/code/community/FireGento/Pdf/Model/Engine/Abstract.php#L980-L1027

To be exact here:
https://github.com/firegento/firegento-pdf/blob/development/src/app/code/community/FireGento/Pdf/Model/Engine/Abstract.php#L1020-L1021

One call for every line of note.

Unfortunately there is no event or anything to change the color. The hacky way would be to insert your change above line 120. Better would be to implement your own engine and just overwrite the method as described in the FAQ:
https://github.com/firegento/firegento-pdf/wiki/FAQs#i-do-not-like-the-standard-engines---how-can-i-write-my-own-engine

How to change the font:
https://github.com/firegento/firegento-pdf/blob/development/src/app/code/community/FireGento/Pdf/Model/Engine/Abstract.php#L1269-L1275

How to change font color:
https://framework.zend.com/manual/1.12/en/zend.pdf.drawing.html#zend.pdf.drawing.text-drawing Example 2

**Comment by 4lternative** [comment]
Thanks for the help. So after a sh*t load of testing things, I got what I want. But it's clearly not really clean ^^ I'll try to write my own engine later. Here is the code I came up with : 

```
[...]

                $page->drawText($tmpNote, $this->margin['left'], $this->y + 30,
                    $this->encoding);
                $this->Ln(15);
            }                        
        }
        $page->setFillColor(Zend_Pdf_Color_Html::color('#990000'))
             ->drawText('1st Line', 90, $this->y + 10, $this->encoding);
                $this->Ln(15);

        $page->setFillColor(Zend_Pdf_Color_Html::color('#990000'))
             ->drawText('2nd line.', 75, $this->y + 8, $this->encoding);
                $this->Ln(15);
        
        $page->setFillColor(Zend_Pdf_Color_Html::color('#000000'))
             ->drawText('', 75, $this->y + 7, $this->encoding);
                $this->Ln(15);

        return $page;        
    }
```

The third line is there to make the footer black again, otherwise he was taking the red color... I've tried to figure out why, but no idea.

Thank you for the help, I really appreciate it, your extension is already great, support even better. 

Cheers
