### ISSUE TITLE
Not working in magento 1.9.2.4

### ISSUE THREAD

**Issue by santoshscotty** [firegento/firegento-pdf#331]
ERROR:        Invalid config field backend model: firegento_pdf/system_config_backend_font
file:                includes/src/Mage_Adminhtml_Block_System_Config_Form.php

**Comment by Schrank** [comment]
Version? What have you done? Cache deleted?

**Comment by santoshscotty** [comment]
yes i have deleted cache of apache as well as magento

**Comment by santoshscotty** [comment]
FireGento_Pdf version is 1.3.0 .. installed via magento connect
after deleting the cache if i go to admin page, configuration, sales , pdf print , am getting 500 internal server error

**Comment by Schrank** [comment]
Please use the development branch from github.

**Comment by Schrank** [comment]
Ah, and recompile, better don'T use the compiler

**Comment by santoshscotty** [comment]
ok ill try from development branch.. Thanks for the response :)
