### ISSUE TITLE
How to translate total labels

### ISSUE THREAD

**Issue by DHYCIX** [firegento/firegento-pdf#332]
Hello!

How do I edit the labels on the bottom part of an invoice, for example?

Is there a CSV file for that somewhere? Otherwise, which file(s) contain the relevant strings?

Thank you very much in advance! I really appreciate your work!

**Comment by sprankhub** [comment]
There are already many issues regarding translation stuff - see https://github.com/firegento/firegento-pdf/issues?utf8=%E2%9C%93&q=is%3Aissue%20translate. If you cannot manage to translate a specific string, feel free to re-open and tell us which string exactly you try to translate.
