### ISSUE TITLE
Mass-Creation of separated invoices

### ISSUE THREAD

**Issue by DavidDaverl** [firegento/firegento-pdf#336]
Dear Firegento-Team and other helping hands,

my tax consultant needs my invoices in separated .PDFs like invoicenumber.pdf - is this somehow possible? I only know the way to select them all in the backend and hit "PDF Rechnungen" which creates one large .PDF file with all invoices - just need to get them separated and with the invoice-number as filename.

I've tried something like 

`$collection = Mage::getResourceModel('sales/order_invoice_collection');
$pdf = Mage::getModel('sales/order_pdf_invoice')->getPdf(array($this));
header("Content-type:application/pdf");
header("Content-Disposition:attachment;filename='invoices.pdf'");`

which results in Fatal error: Call to a member function getStoreId() on a non-object in app/code/community/FireGento/Pdf/Model/Engine/Invoice/Default.php on line 64 - so it seems there are some parameters missing.

Has anyone a solution for the whole problem or a fix for my try? Would help me very much!

Thank you in advance and best greets, David

**Comment by sprankhub** [comment]
What you basically need to do is:

1. Get your invoices (you got that one):

        $collection = Mage::getResourceModel('sales/order_invoice_collection');

2. Iterate over all invoices and save them somewhere (mind the parameter of `getPdf` - you mixed that one up):

        $varDir = Mage::getBaseDir('var');
        foreach ($collection as $invoice) {
            $pdf      = Mage::getModel('sales/order_pdf_invoice')->getPdf(array($invoice));
            $filename = $varDir . DS . Mage::helper('firegento_pdf')->getExportFilename('invoice', $invoice);
            $pdf->save($filename);
        }

This will save all invoices straight into the var folder.

**Comment by Schrank** [comment]
This is a duplicate of https://github.com/firegento/firegento-pdf/issues/182
