### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by mindmagic** [firegento/firegento-pdf#337]
The extension installed fine and is visible in the back end, but any changes do not become visible in the actual pdf´s at all? Please help!

**Comment by sprankhub** [comment]
So your PDF still looks like the default Magento one although you changed the engine in the system configuration?

If this is the case, this is most probably a rewrite conflict. You can use [n98-magerun](https://github.com/netz98/n98-magerun) to check if this is the case.

**Comment by mindmagic** [comment]
Thank you, that is a little out of my skill range. Lets say it is a rewrite conflict, how do i fix it?

**Comment by Schrank** [comment]
1. Install magerun (as described on their page)
2. run `n98-magerun.phar dev:module:rewrite:conflicts`
3. fix the rewrite conflict - if you are a developer, it is time to get one or learn it.

More on this:
http://www.webshopapps.com/blog/2010/11/resolving-magento-extension-conflicts/
