### ISSUE TITLE
Unwanted line break in order comments

### ISSUE THREAD

**Issue by yasharkkk** [firegento/firegento-pdf#338]
Hey there,

we have problem with the invoice comments in the pdf. The comment created in magento is a simple text with two lines. But in the pdf which gets created a line break is made right in the sentence.

The comment looks like this:
Die Ware bleibt bis zur vollständigen Bezahlung unser uneingeschränktes Eigentum.
Wir danken für Ihren Auftrag und das uns entgegen gebrachte Vertrauen.

But in the invoice pdf the comment is like this:
Die Ware bleibt bis zur vollständigen Bezahlung unser uneingeschränktes Eigentum.
Wir danken für Ihren
Auftrag und das uns entgegen gebrachte Vertrauen.

I even checked the comment in the database, but there's nothing strange to see, just the comment. 

Greetings

**Comment by Schrank** [comment]
Are you sure there is no hidden white space in it?

**Comment by yasharkkk** [comment]
Yeah, I already checked that but there's nothing! The comment you see in here was copied right out of the database so if there would be something extra it would be visible...

This is really puzzeling to me as it just doesnt make any sense!

**Comment by sprankhub** [comment]
Sorry for the delay!

I just checked it with the latest development branch. I added your two sentences under the system configuration `sales_pdf/invoice/note`. Works as it should:

![image](https://cloud.githubusercontent.com/assets/930199/24553323/354befb6-162a-11e7-842d-5a3eb368e788.png)
