### ISSUE TITLE
Order Confirmation PDF Layout

### ISSUE THREAD

**Issue by horibu** [firegento/firegento-pdf#340]
Hi there,

I have installed the firegento-pdf extension in my shop and I am facing some issues with the order confirmation PDFs ( so not the invoices).  In the backend I have selected everywhere the "Standard Deutschland" PDF Engine but it seems that the pdf attachement sent in the email is still styled like the default magento PDF.

**Comment by sprankhub** [comment]
We currently do not do anything with the order PDFs. We only change the invoice, shipment and creditmemo design. Once #297 is merged, the order PDFs are handled as well.
