### ISSUE TITLE
Drop PHP 5.3/4/5 Support 

### ISSUE THREAD

**Issue by Schrank** [firegento/firegento-pdf#341]
I would love to drop PHP 5 support at all, but there are a lot of people out there which still use PHP5.

What about dropping PHP 5.5 support?

**Comment by sprankhub** [comment]
When we drop PHP 5.3/5.4/5.5 support, we would also drop support for Magento < 1.9. I would be fine with it if there were bummer features we could only implement when dropping support for these versions, but I think this is not the case. Even though I encourage people to use newer PHP versions, I do not see any advantage in explicitely dropping support.

Feel free to explain the advantages and re-open if needed ;-)
