### ISSUE TITLE
Magento ignores the pdf engine selection for invoice

### ISSUE THREAD

**Issue by fallahdoust** [firegento/firegento-pdf#342]
Magento Version 1.9.2.2
FireGento_Pdf Version 1.3.0
When for "Rechnung" the pdf engine is set to "Standard Deutschland" the system will ignore the selection and invoices are generated in the "Standard Magento" style.
![2017-02-25 12 51 51 am](https://cloud.githubusercontent.com/assets/26015651/23325431/88f698f0-faf5-11e6-8690-0ed591bfc2ec.png)

The selection of pdf engine works fine for both "Versand" and "Rechnungskorrektur".

**Comment by Schrank** [comment]
Due to the fact that it works everywhere else, might it be, that you have some other extension installed which rewrites the invoice_pdf? It shouldn't be the cache. No other idea currently.
