### ISSUE TITLE
Problem with Discount

### ISSUE THREAD

**Issue by Schrimpkutter** [firegento/firegento-pdf#347]
Hello i have a Problem with Firegento using discounts in the invoice.Im using custom options in the order.
![bildschirmfoto 2017-04-03 um 13 35 16](https://cloud.githubusercontent.com/assets/26871137/24607499/68662f3e-1872-11e7-9361-caa1b6243f70.png)
If you look on the uploaded png you will the the first line is correct (Menge, Brutto, Netto).

Then the Problems:
**Nettosumme 37,65 € (not correct)**
zzgl. 19% MwSt. 3,35 € (correct)
**Nettosumme 37,65 € (not correct, this should be Bruttosumme and 21,00€)**
Rabatt -20,00 € (correct)
Gesamtbetrag 1,00 € (correct)

Does someone have a idea why this happens and how i can fix the problem ? 

I have tried to update on the newest version 1.3 but then a error appeared: PHP Fatal error:  Call to undefined method FireGento_Pdf_Helper_Data::getExportFilename() in app/code/community/FireGento/Pdf/controllers/Adminhtml/Sales/Order/InvoiceController.php on line 49
Im using Magento 1.9.2.3

Greetings

**Comment by Schrank** [comment]
Can you please try with the develop branch from here?

**Comment by Schrimpkutter** [comment]
My last try was the https://codeload.github.com/firegento/firegento-pdf/zip/master from here.
So i just copy pasted the files from the download to my magento dir. Then the error appeared.
The i tried updating over magento connect, same problem. I also reinstalled it over magento connect. Nothing worked for me so i did a roleback on the dirs.

**Comment by Schrank** [comment]
https://codeload.github.com/firegento/firegento-pdf/zip/development

**Comment by Schrimpkutter** [comment]
After copy and cleaning Cache the same error appears.

**Comment by Schrank** [comment]
hmmm, the method exists:
https://github.com/firegento/firegento-pdf/blob/development/src/app/code/community/FireGento/Pdf/Helper/Data.php#L351

And it is also in the code - might it be, that you have overwritten parts of the module in `app/code/local`?

**Comment by Schrimpkutter** [comment]
I dont think that i overwritten parts in local. At this moment there are 3 Package installed if i open magento connect:
FireGento_GermanSetup
FireGento_Pdf
FireGento_MageSetup

So if i uninstall the 3 packages over magento connect, all other settings and configs will be deleted and i could try to install it again step by step ?

**Comment by Schrank** [comment]
I don't use Magento Connect, therefore I don't know. But I guess the settings are not deleted.

Can you check, whether the file exists in app/code/local/FireGento/Pdf/Helper/Data.php ?

But this sounds like a problem on your side. If you need payed help, please write me or @sprankhub an email.

And a tipp: You don'T need GermanSetup AND MageSetup. GermanSetup is deactivated by MageSetup :) because it is the replacement
