### ISSUE TITLE
Marketplace plugin: Multi vendor invoice

### ISSUE THREAD

**Issue by edudemy** [firegento/firegento-pdf#348]
Hi Firegento Team,  

Is there a way to generate a vendor specific invoice, packing slip in a marketplace multi-vendor store.

**Comment by Schrank** [comment]
Not out of the box.

[You can implement your own engine](https://github.com/firegento/firegento-pdf/wiki/FAQs#i-do-not-like-the-standard-engines---how-can-i-write-my-own-engine) or manipulate the imprint (which is a horrible idea!).

If you need help, tell @sprankhub or me.
