### ISSUE TITLE
Bundle Product Issue

### ISSUE THREAD

**Issue by anjenehm** [firegento/firegento-pdf#351]
We have Bundle Products included with configurable products or simple products. When we creat a invoice and print them we got the same price for each product in the bundle and subtotal equals zero. How can we solve this issue?

![image](https://cloud.githubusercontent.com/assets/7089704/26352570/a54f0ada-3fbc-11e7-968a-78a766774a91.png)

**Comment by sprankhub** [comment]
Are you sure you are using the latest development branch? If not, please try it. If it also happens there, please also post a screenshot of the ordered products in the admin grid.

**Comment by anjenehm** [comment]
Firegento PDF v 1.3.0

![image](https://cloud.githubusercontent.com/assets/7089704/26390530/3a1b9a78-405f-11e7-9bfc-cb93f8e3b96e.png)
![image](https://cloud.githubusercontent.com/assets/7089704/26390538/48c0a208-405f-11e7-8bd2-2247eb8b899f.png)

Thank you very much for your support

**Comment by sprankhub** [comment]
Could you please check if you still have this issue with the latest development branch? Unfortunately, the release is kind of old.

**Comment by anjenehm** [comment]
I removed everything and re-uploaded the module and viola everything works fine again! Thank you so much!

**Comment by sprankhub** [comment]
Glad this solved it!
