### ISSUE TITLE
Den Header auch auf Seite 2 und ++ einfügen

### ISSUE THREAD

**Issue by happyfabric** [firegento/firegento-pdf#352]
Hallo, ich würde gerne den header auch auf Folgeseiten der pdf einfügen. Gerade die Bestellnummer wäre mir wichtig. So das im Falle eines Falles auch eine Seite 2 oder 3 etc wieder der richtigen Bestellung zugeordnet werden kann.

Schön wäre es auch, zwischen den einzelnen Positionen Linien oder farbliche Wechsel einzufügen und die Schrift etwas größer zu einzustellen um es etwas übersichtlicher zu machen.

Gibt es hierzu eine Lösung?
Grüße
Markus

**Comment by Schrank** [comment]
Hi Markus,

there is no solution for that. I think implementing your own engine and playing around with the methods should bring you there. But sounds like a lot of work. It might be easier to built an HTML/CSS2PDF solution like https://github.com/dompdf/dompdf

So for FireGento_PDF the way to go would be to copy the Invoice.php and then add all methods from Abstract.php you need.

New pages are generated here:
https://github.com/firegento/firegento-pdf/blob/development/src/app/code/community/FireGento/Pdf/Model/Engine/Abstract.php#L797

so you need to add the header after a new page.

To get lines between the items and change the color have a look into https://github.com/firegento/firegento-pdf/blob/development/src/app/code/community/FireGento/Pdf/Model/Items/Default.php#L37
