### ISSUE TITLE
Receiving email and pdf invoice with Shipping but no email at all with Invoice

### ISSUE THREAD

**Issue by lovelife85** [firegento/firegento-pdf#353]
Using Fooman Attatchments with Firegento. And when i send a Shipment email to customer it gets delivered with PDF in "Standard Germany" style (the nicer looking one ;-).

But sending an Invoice email doenst deliver any email to customer. Keeping it on standard magento pdf engine will get the email delivered and with the ugly pdf invoice attatched from magento. So keeping the PDF engine for Invoice on Standard Germany wont deliver the email. Id like to have the standard germany pdf for invoice as well. Thats my issue.

Quite weird, something must be blocking it? Couldnt find anything in the logs.

Your help is apprecaited!
Kudos to Firegento for making this available

**Comment by Schrank** [comment]
Never heard of the issue and I'm using this combination in some projects. So imho there is only one way: dig into the code and find the issue :-/

Check that the log is running, error_reporting is on (not display_errors!) and check system.log, exception.log, reports and apache/php error log.

If this doesn't help, imho this is a good case for paid support.

Sorry for no better news.

**Comment by lovelife85** [comment]
Nothing shows in my logs Schrank. I thought Fooman Email Attatchment and Firegento PDF were recommended to use. There isnt any other email attatchement extension. So somewhere Fooman extension doenst attatch and send the pdf invoice email when "standard germany" is selected for invoice in Firegento.

**Comment by Schrank** [comment]
Correct assumption. The question is why, because you seems the first with this problem. What I can offer you is to dig into your code and find the problem, and write you an invoice.

One alternative would be: you find the problem, if it is a problem with foomans or our extension we are looking forward to a PR :-)
