### ISSUE TITLE
Rechnungen BEnutzerkonto

### ISSUE THREAD

**Issue by reproplan** [firegento/firegento-pdf#356]
Hallo Rouven,

ich hätte hier mal eine technische Frage zu deinem Modul. 

Die Aufträge werden ja in Magento erst als „Erledigt“ angezeigt, wenn die Rechnung auch über das System eingereicht wurde, ich möchte aber keine Rechnung mit Magento erstellen, sondern möchte
dafür unsere Faktura benutzen.

Ist es möglich, die Magento Rechnungen automatisch in einen anderen Ordner zu legen, so dass die Besteller über sein Benutzerkonto nicht mehr an die Magento Rechnungen kommen kann???

Ich würde dann die Rechnungen für die erbrachten Leistungen in unserer Faktura erstellen und diese PDF-Dateien dann in den dafür vorgesehen Ordner via FTP ablegen, sodass der Besteller über sein Benutzerkonto an die verbindlich richtige Rechnung kommt.

Kann ich das mit diesem Modul abdecken???

viele Grüße,
Matze

**Comment by Schrank** [comment]
Nein. Magento erzeugt die Rechnung erst beim Klick auf den Link, d.h. es gibt keine echten PDF-Dateien.

Aber du kannst im Frontend einfach das Template ändern, prüfen ob die Datei existiert und dann die Rechnung verlinken, dann bekommst dein Kunde dein Rechnungs-PDF.

Dafür brauchst du aber dieses Modul nicht.

**Comment by reproplan** [comment]
vielen Dank für deine Rückmeldung, so einfach kann ich das aber leider nicht, weiß leider nicht in welcher Datei ich da ansetzen sollte :-) 

VG
Matze

**Comment by Schrank** [comment]
Dann empfehle ich einen kompetenten Entwickler zu finden, bei FireGento findest du ggf. welche, schreib gerne eine Mail an contact@firegento.com dann leite ich es an unsere Mitglieder weiter.
