### ISSUE TITLE
fatal error: Call to a member function glyphNumbersForCharacters() on null app/code/core/Mage/Sales/Model/Order/Pdf/Abstract.php on line 105

### ISSUE THREAD

**Issue by itsolon** [firegento/firegento-pdf#363]
Problems with firegento PDF
our firegento Installation does not work all time
if i generate invoice and print out then the button print works only sometimes as expected
(for same order sometimes i get Standard PDF and sometimes the other one)
although i have set up right and PDF engine is Standard firegento 
very often i get http 500 error when printing shipping PDF
it is weird
i cannot figure out when it happens
ok. what i have
Debian 8 with php 5.6 
then the behaviour is like i describe and the error is following

Fatal error: Call to a member function glyphNumbersForCharacters() on null in /var/www/vhosts/ DOMAIN.COM /httpdocs/app/code/core/Mage/Sales/Model/Order/Pdf/Abstract.php on line 105

if i Change Installation to php 7, (i installed inchoo php 7 Extension for that, the error Output is more detailed 
perhaps someone can help

Fatal error: Uncaught Error: Call to a member function glyphNumbersForCharacters() on null in /var/www/vhosts/DOMAIN.COM/httpdocs/app/code/core/Mage/Sales/Model/Order/Pdf/Abstract.php:105 Stack trace: #0 /var/www/vhosts/DOMAIN.COM/httpdocs/app/code/community/FireGento/Pdf/Model/Engine/Abstract.php(1347): Mage_Sales_Model_Order_Pdf_Abstract->widthForStringUsingFontSize(' Versand -', NULL, 10) #1 /var/www/vhosts/DOMAIN.COM/httpdocs/app/code/community/FireGento/Pdf/Model/Engine/Abstract.php(654): FireGento_Pdf_Model_Engine_Abstract->_prepareText('Versand - Paket', Object(Zend_Pdf_Page), NULL, 10, 80) #2 /var/www/vhosts/DOMAIN.COM/httpdocs/app/code/community/FireGento/Pdf/Model/Engine/Abstract.php(416): FireGento_Pdf_Model_Engine_Abstract->insertHeader(Object(Zend_Pdf_Page), Object(Mage_Sales_Model_Order), Object(Mage_Sales_Model_Order_Shipment)) #3 /var/www/vhosts/DOMAIN.COM/httpdocs/app/code/community/FireGento/Pdf/Model/Engine/Shipment/Default.php(70): FireGento_Pdf_Model_Engine_Abstract->insertAddressesAndH in /var/www/vhosts/DOMAIN.COM/httpdocs/app/code/core/Mage/Sales/Model/Order/Pdf/Abstract.php on line 105

**Comment by sprankhub** [comment]
I could reproduce the issue. It happens when you hide the payment method, but show the shipping method. Will fix it shortly.
