### ISSUE TITLE
Layout Problem with creditmemo

### ISSUE THREAD

**Issue by spdizzle** [firegento/firegento-pdf#367]
Hello,
I have the problem that, in the german creditmemo pdf, the "netto"price is in the column of the tax. How to change that? 
Thanks

**Comment by sprankhub** [comment]
You probably changed the order of the invoice columns, which affects the order of the credit memo columns as well. In old versions, the credit memo columns did not respect the ordering correctly. I think this issue should be solved when you update to the [latest development branch](https://github.com/firegento/firegento-pdf/archive/development.zip).
