### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by bloggerpact** [firegento/firegento-pdf#368]
Hey,
thanks for your plugin and i just installed and getting this error

Fatal error: Uncaught Error: Call to a member function getCreatedAt() on null in /www/app/code/community/FireGento/Pdf/Helper/Data.php:266 Stack trace: #0 /www/app/code/community/FireGento/Pdf/controllers/Sales/OrderController.php(126): FireGento_Pdf_Helper_Data->getExportFilename('invoice', NULL) #1 /www/app/code/community/FireGento/Pdf/controllers/Sales/OrderController.php(53): FireGento_Pdf_Sales_OrderController->printDocument('invoice') #2 /www/app/code/core/Mage/Core/Controller/Varien/Action.php(418): FireGento_Pdf_Sales_OrderController->printInvoiceAction() #3 /www/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('printInvoice') #4 /www/app/code/community/BalkeTechnologies/StoreMaintenance/Controller/Router/Stan in /www/app/code/community/FireGento/Pdf/Helper/Data.php on line 266

when i click on **Print All Invoices** using the customer account

![image](https://user-images.githubusercontent.com/22036537/35189971-87d8baf8-fe7c-11e7-9084-0afcc579ee46.png)

**Comment by Schrank** [comment]
Thanks for the report @bloggerpact.

Are you running on the current develop branch?

**Comment by sprankhub** [comment]
I just checked this with the latest development branch and could not reproduce it.
