### ISSUE TITLE
Storeview change Footer / anderer Footer beim Storeview

### ISSUE THREAD

**Issue by dave729** [firegento/firegento-pdf#373]
Hallo, kurze frage, wie kann ich einstellen das bei den verschiedenen Storeviews andere Footers kommen. Also immer eine andere Adresse usw.?
Könnt Ihr mir bitte helfen?

Hello, i have a question, how can I adjust the different Storeviews other footers come. So always a different address, etc.?
Please help me

**Comment by Schrank** [comment]
The footer is generated by the MageSetup imprint, which can be found in the configuration:

    General > General > Imprint

Whatever you put there for the different store views is printed on the pdfs.

HTH

**Comment by dave729** [comment]
yes but, can i this change for the Storeviews?
example:
 < general>
            < imprint>
                < company_first>Store1</ company_first>
		< street>Store1</ street>
            </ imprint>
< /general>
and for store2? I don`t no
