### ISSUE TITLE
Storeview Change Footer Magento1 config.xml

### ISSUE THREAD

**Issue by dave729** [firegento/firegento-pdf#374]
Hello, now for the second, because the other has closed this. I have version Magento 1.9.3.8 and can not change the footer for different stores. I have entered it in the /magento/app/code/community/FireGento/Pdf/etc/config.xml. How can I enter the second and third store here?

        < general>
            < imprint>
                < company_first>company1</ company_first>
		< street>street1</ street>
                < zip>zip1</ zip>
                < city>City1</ city>
                < telephone>tele1</ telephone>
                < email>email1</ email>
                < web>web1</ web>
                < tax_number>tax1</ tax_number>
                < vat_id>vat1</ vat_id>
                < court>court1</ court>
                < ceo>ceo1</ ceo>
                < register_number>register1</ register_number>
                < bank_account_owner>bank1</ bank_account_owner>              
                < bank_name>bankname1</ bank_name>
                < swift>swift1</ swift>
                < iban>iban1</ iban>
            </ imprint>
        </ general>

and für Store2 and Store3?

Please do not close again!

**Comment by kkrieger85** [comment]
Hi @dave729 you have to store any data in config.xml

You have to store your store-specific imprint data by selecting store view in Backend 
<img width="242" alt="bildschirmfoto 2018-05-12 um 15 43 36" src="https://user-images.githubusercontent.com/4435523/39957944-b6240120-55fb-11e8-9d09-97ded9bdeb10.png">

Then you can store different imprint data for different shops.

**Comment by dave729** [comment]
I just found my mistake. Have Firegento pdf installed but not Firegento Mage.
That's why I did not have this entry. Now it's working :-)
Srry

**Comment by Schrank** [comment]
Der Vollständigkeit halber:

https://www.webguys.de/magento-1/tuerchen-01-konfiguration-unnoetig

German blog article written by me about how to add different configurations for default, store and website to configuration via xml.
