### ISSUE TITLE
Magento 2 Support

### ISSUE THREAD

**Issue by 123bistami** [firegento/firegento-pdf#378]
Hey guys, 
in magento 2 extension folder structur is different than in version 1, maybe you can fix it for use in Magento 2. 

Best Regards

**Comment by Schrank** [comment]
😂😂😂 No.


M1 and M2 are not compatible in any way. This extension will never be useable in M2.

I don't know how complete or even started https://github.com/firegento/firegento-pdf2 is, have a look there.

**Comment by 123bistami** [comment]
hello,
the zf1 pdf file is compatible with magento 2, both uses zf1 to write the pdf

**Comment by Schrank** [comment]
This might be the case, but we would have to reimplement the whole module again. And there are lots of reasons we don't want to migrate the extension to M2 but instead write a new one. One big reason is: Zend_Pdf is a bad basis for everything but instead we would use dompdf or something alike so one can implement the template in html for invoices, creditmemos, etc.
