### ISSUE TITLE
Add billing address to shipment

### ISSUE THREAD

**Issue by kledy** [firegento/firegento-pdf#379]
I need to add the billing address at the bottom of the order items, so that the recipient know, who have ordered this shipment. Is it possible?

**Comment by Schrank** [comment]
Not out of the box.

But you could implement an observer which adds it to the note section.

https://github.com/firegento/firegento-pdf/wiki/FAQs#how-can-i-add-notes-to-the-pdfs-programmatically

Hope this answers the question.
