### ISSUE TITLE
Change address bar to HTML

### ISSUE THREAD

**Issue by lifeenergy-eu** [firegento/firegento-pdf#381]
How to change the TEXT type of an Sender Address Bar to HTML. In this area I need to put our company information which is not in only one line but need to be in several lines (HTML preferable).

**Comment by Schrank** [comment]
Hey, thanks for your issue!

Unfortunately is FiregentoPDF completely written without HTML, we have nice plans to change it, but family and stuff, you know 😅 

That said, to change the address bar, [you can implement your own engine](https://github.com/firegento/firegento-pdf/wiki/FAQs#how-can-i-put-some-fancy-stuff-wherever-i-want-to-without-writing-my-own-engine) and overwrite this method:
https://github.com/firegento/firegento-pdf/blob/development/src/app/code/community/FireGento/Pdf/Model/Engine/Abstract.php#L243-L256

**Comment by lifeenergy-eu** [comment]
Haha family is most important so I understand it completely. 

I am reopen the case since the need for HTML is not so much important and I maybe missed the proper heading of the case.

Your existing field called NOTE is multi-line text which is quite fine to me :)
How can we change sender address bar to the same as NOTE?

**Comment by sprankhub** [comment]
The explanation by @Schrank is also perfectly valid for this case, @lifeenergy-eu. In the end, you need to rewrite the method @Schrank mentioned. The best way to do this is to write a custom engine.
